Repository canonical/charmhub.io, pull requests merged in 2020-10, with the labels that each got.

#428 Use production API
  .env
Labels: Review: Code +1, Review: QA +1

#426 Add dynamic get-in-touch form
  static/js/src/base/base.js
  static/js/src/base/dynamic-contact-form.js
  static/js/src/public/store/filters.js
  static/sass/_pattern_grid.scss
  static/sass/_pattern_p-button.scss
  static/sass/_pattern_p-modal.scss
  static/sass/styles.scss
  templates/base_layout.html
  templates/partial/_footer.html
  templates/partial/_get-in-touch.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#431 Mocked data for actions
  templates/details/actions.html
  webapp/store/logic.py
  webapp/store/mock.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#439 Update details history page
  package.json
  static/js/src/public/details/history/index.js
  static/js/src/public/details/history/tableShowMore.js
  static/sass/_pattern_p-button.scss
  templates/details/history.html
  webpack.config.entry.js
  webpack.config.rules.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#440 History mocked data
  templates/details/history.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#438 Build details actions page
  .eslintrc.js
  static/js/src/base/dynamic-contact-form.js
  static/js/src/libs/highlight-nav.js
  static/sass/styles.scss
  templates/details/actions.html
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#449 Remove husky
  package.json
  yarn.lock
Labels: Review: Code +1

#452 Obtain library docstrings
  requirements.txt
  templates/details/libraries.html
  webapp/helpers.py
  webapp/store/data/library_a.py
  webapp/store/data/library_b.py
  webapp/store/logic.py
  webapp/store/mock.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#451 Migrate from LibSass to Dart Sass
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#453 Fix squircle icons black edge
  static/sass/_charmhub_p-header.scss
  static/sass/_pattern_p-card.scss
  templates/details/_details-header.html
  templates/partial/_entity-card.html
Labels: Review: Code +1, Review: QA +1

#455 Change details pages layout to 90rem
  static/sass/_pattern_grid.scss
  static/sass/charmhub_utils.scss
  static/sass/styles.scss
  templates/details/_details-header.html
  templates/details/_details-tab-navigation.html
  templates/details/actions.html
  templates/details/configure.html
  templates/details/docs.html
  templates/details/history.html
  templates/details/libraries.html
  templates/details/overview.html
  templates/partial/_entity-card.html
  templates/publisher/bundles.html
  templates/publisher/charms.html
  templates/topics/kubernetes.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#457 Remove terser plugin
  package.json
  webpack.config.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#462 Fix publisher views
  templates/partial/_header-publisher-packages.html
  templates/partial/_tabs-publisher-packages.html
  templates/publisher/bundles.html
  templates/publisher/charms.html
Labels: Review: Code +1, Review: QA +1

#464 Get real Discourse docs for Charms
  .github/workflows/pr.yml
  package.json
  templates/details/_details-tab-navigation.html
  templates/details/empty-docs.html
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#465 Integration page
  Dockerfile
  package.json
  static/js/src/public/details/integrate/index.js
  static/sass/_pattern-p-integration-charts.scss
  static/sass/styles.scss
  static/sass/swiper-overrides.scss
  templates/details/_desktop-integration-chart.html
  templates/details/_small-integration-chart.html
  templates/details/integrate.html
  webapp/store/views.py
  webpack.config.entry.js
  webpack.config.rules.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1
