Repository canonical/charmhub.io, pull requests merged in 2020-03, with the labels that each got.

#1 Set up homepage
  static/sass/_charmhub_footer.scss
  static/sass/_charmhub_sidenav.scss
  static/sass/_pattern_p-card.scss
  static/sass/_pattern_p-link.scss
  static/sass/_pattern_p-strip.scss
  static/sass/styles.scss
  templates/base_index.html
  templates/index.html
  templates/partial/_footer.html
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#4 Refactor the card pattern to utilise Vanilla more
  static/sass/_pattern_p-card.scss
  static/sass/styles.scss
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#6 Add husky and lint-staged
  package.json
  static/sass/_charmhub_footer.scss
  static/sass/_charmhub_sidenav.scss
  static/sass/_pattern_p-link.scss
  static/sass/_pattern_p-strip.scss
  static/sass/styles.scss
  yarn.lock
Labels: Review: Code +1

#7 Add some filter handling
  templates/index.html
  webapp/app.py
  webapp/helpers.py
Labels: Review: Code +1

#5 Add side navigation basic functionality
  static/js/README.md
  static/sass/_charmhub_sidenav.scss
  static/sass/_pattern_p-card.scss
  static/sass/_patterns_side-navigation.scss
  static/sass/styles.scss
  templates/base_index.html
  templates/index.html
  templates/partial/_footer.html
  templates/partial/_navigation.html
  templates/partial/_side-navigation.html
  webapp/app.py
  webapp/helpers.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#9 Update surus on homepage
  static/sass/_charmhub_footer.scss
  static/sass/_pattern_p-strip.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8 Multistage docker image
  .dockerignore
  Dockerfile
  package.json
Labels: Review: Code needed, Review: QA needed

#10 1270 details page header
  .eslintrc.js
  .gitignore
  package.json
  static/js/tabs.js
  static/sass/_charmhub_p-group.scss
  static/sass/_charmhub_p-header.scss
  static/sass/_charmhub_p-series-tag.scss
  static/sass/_pattern_p-strip.scss
  static/sass/styles.scss
  templates/base_index.html
  templates/details.html
  templates/partial/_tab-actions.html
  templates/partial/_tab-configuration.html
  templates/partial/_tab-contribute.html
  templates/partial/_tab-docs.html
  templates/partial/_tab-history.html
  templates/partial/_tab-integrations.html
  templates/partial/_tab-overview.html
  templates/partial/_tabs-navigation.html
  webapp/app.py
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#15 Refactor overview chart mark-up slightly
  static/sass/_charmhub_p-group.scss
  static/sass/styles.scss
  templates/partial/_tab-overview.html
Labels: Review: Code +1, Review: QA +1

#14 Replace sass-lint with stylelint
  .stylelintrc
  package.json
  run
  static/sass/_charmhub_footer.scss
  static/sass/_charmhub_p-header.scss
  static/sass/_charmhub_p-series-tag.scss
  static/sass/_pattern_p-accordion.scss
  static/sass/_pattern_p-strip.scss
  static/sass/_patterns_side-navigation.scss
  static/sass/styles.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#17 Add charmhub logo to the navigation
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#16 Add configuration tab
  static/sass/_pattern_p-table-of-contents.scss
  static/sass/styles.scss
  templates/partial/_tab-configuration.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#13 Add actions tab on the details page
  static/sass/_pattern_p-accordion.scss
  static/sass/styles.scss
  templates/details.html
  templates/partial/_tab-actions.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#20 Convert to floats instead of flex
  static/sass/_pattern_p-card.scss
  static/sass/styles.scss
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#19 Add docs tab
  templates/partial/_tab-configuration.html
  templates/partial/_tab-docs.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#21 Add integrations tab
  static/sass/styles.scss
  templates/index.html
  templates/partial/_tab-integrations.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#22 Add bundles page details header
  static/sass/_charmhub_p-bundle-icons.scss
  static/sass/_pattern_p-card.scss
  static/sass/_pattern_p-media-object.scss
  static/sass/styles.scss
  templates/details.html
  templates/partial/_tabs-navigation.html
  templates/partial/_top-bundles.html
  webapp/app.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#23 Add history tab
  static/sass/styles.scss
  templates/partial/_tab-history.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#24 Add contribute tab
  templates/partial/_tab-contribute.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#25 Make charmhub specific config, make app.py more generic
  templates/base_layout.html
  templates/details.html
  templates/index.html
  tests/test_routes.py
  webapp/app.py
  webapp/charmhub.py
Labels: Review: Code +1, Review: QA +1

#26 Dotrun snap support
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#28 Small fixes
  static/sass/styles.scss
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#33 Update bundle icon
  static/sass/_charmhub_p-bundle-icons.scss
  static/sass/_pattern_p-media-object.scss
  static/sass/styles.scss
  templates/details.html
  templates/partial/_tabs-navigation.html
  templates/partial/_top-bundles.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#34 Add grey icons
  static/sass/_pattern_p-card.scss
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#39 Add dummy data to python
  templates/404.html
  templates/500.html
  templates/details.html
  templates/index.html
  templates/partial/_entity-card.html
  templates/partial/_tab-overview.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1
