Repository canonical/charmhub.io, pull requests merged in 2020-12, with the labels that each got.

#699 Implement visual changes to integrate chart
  static/js/src/public/details/integrate/index.js
  static/sass/_pattern_p-modal.scss
  templates/details/_small-integration-chart.html
  templates/details/integrate.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#690 Add summary and description to the charm overview page
  static/js/src/libs/truncate-string.js
  static/js/src/public/details/index.js
  static/js/src/public/details/libraries/index.js
  templates/details/overview.html
  webapp/helpers.py
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#701 Remove hardcoded actions
  templates/details/actions.html
Labels: Review: Code +1

#704 Bug fixes
  templates/details/_details-header.html
  templates/partial/_channel-map.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#703 Fix required field
  templates/details/actions.html
Labels: Review: Code +1, Review: QA +1

#708 Fix side navigation to be able to close it on mobile
  static/sass/_pattern_p-navigation.scss
  templates/about/about_layout.html
  templates/details/libraries/libraries_layout.html
Labels: Review: Code +1, Review: QA +1

#706 Update featured charm publisher
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#712 Update feature list
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#710 Update publisher listing page
  static/js/src/publisher/listing-page.js
  static/sass/_pattern_grid.scss
  static/sass/_pattern_p-list.scss
  static/sass/charmhub_utils.scss
  templates/publisher/charms.html
  templates/publisher/listing.html
  templates/publisher/publisher_layout.html
  templates/publisher/settings.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#718 Remove wordpress from featured charms
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#719 Add special command for specific charms
  templates/partial/_channel-map.html
  webapp/feature.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#717 Add mobile filters to store page
  static/js/src/public/store/charms.js
  static/sass/_charmhub_p-filter.scss
  static/sass/_charmhub_p-layout-store.scss
  static/sass/_pattern_p-icon.scss
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#723 Fix master GH checks
  .github/workflows/master.yml
  .github/workflows/pr.yml
  README.md
Labels: Review: Code +1

#726 Update feature charm summary
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#720 Update library page display on mobile
  static/sass/_pattern_p-image.scss
  static/sass/_pattern_p-list.scss
  templates/details/libraries/libraries_layout.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#732 Update github pr template and add hacking.md file
  .github/pull_request_template.md
  HACKING.md
  README.md
Labels: Review: Code +1

#734 update HACKING.md
  HACKING.md
Labels: Review: Code +1

#737 Fix moving filters when loading homepage
  static/sass/_charmhub_p-layout-store.scss
Labels: Review: Code +1, Review: QA +1

#738 Update discourse summary
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#739 Only request necessary fields per endpoint
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#740 Update cassandra command
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#742 copy list before extend
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#744 Update feature
  webapp/feature.py
Labels: Review: Code +1
