Repository canonical/charmhub.io, pull requests merged in 2020-11, with the labels that each got.

#474 Remove mock for actions
  templates/details/_details-tab-navigation.html
  webapp/store/logic.py
  webapp/store/mock.py
Labels: Review: Code +1, Review: QA +1

#475 Remove useless tag
  static/js/src/public/details/integrate/index.js
Labels: Review: Code +1 (with changes)

#473 Add cookie policy module
  package.json
  static/js/src/base/base.js
  static/sass/styles.scss
  templates/partial/_footer.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#491 Update discourse links
  templates/details/docs.html
  templates/details/overview.html
  templates/docs/search.html
  templates/partial/_footer.html
  templates/partial/_navigation.html
  templates/thank-you.html
  webapp/docs/views.py
  webapp/helpers.py
  webapp/tutorials/views.py
Labels: Review: Code +1, Review: QA +1

#489 Add platform filter
  static/js/src/public/store/filters.js
  static/sass/_charmhub_p-layout-store.scss
  templates/partial/_filters.html
  templates/store.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#478 Add swap between channel easy
  static/js/src/public/details/channelMap.js
  templates/details/_details-header.html
  templates/details/_details-tab-navigation.html
  templates/details/actions.html
  templates/details/docs.html
  templates/details/empty-docs.html
  templates/partial/_channel-map.html
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#493 Add logo for docsstring
  static/sass/_pattern_p-icon.scss
  templates/details/libraries/libraries_layout.html
Labels: Review: Code +1, Review: QA +1

#495 Add link to tutorial for docs
  templates/details/empty-docs.html
Labels: Review: Code +1

#498 Default empty readme to empty string
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#499 Add highlight js for library color syntax
  package.json
  static/js/src/base/highlight.js
  templates/details/libraries/library.html
  webpack.config.entry.js
  webpack.config.rules.js
  yarn.lock
Labels: Review: Code +1 (with changes), Review: QA +1

#503 Highlight channel on hover
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#496 Add feature charms
  templates/partial/_filters.html
  templates/store.html
  webapp/feature.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#505 Fix up charm actions tab
  static/sass/_pattern_p-list.scss
  templates/details/actions.html
  templates/details/configure.html
Labels: Review: Code +1, Review: QA +1

#506 Update typography on charm libraries template
  static/sass/_pattern_p-typography.scss
  static/sass/styles.scss
  templates/details/libraries/library.html
Labels: Review: Code +1, Review: QA +1

#507 Fix None signature
  templates/details/libraries/library.html
Labels: Review: Code +1, Review: QA +1

#509 Add help icon to Publisher suggests in libraries tab
  templates/details/libraries/libraries_layout.html
Labels: Review: Code +1, Review: QA +1

#517 Remove discoures authentication
  konf/site.yaml
  webapp/helpers.py
Labels: Review: Code +1, Review: QA +1

#521 Update homepage header
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#527 Clear search reload the page
  static/js/src/public/store/filters.js
Labels: Review: Code +1, Review: QA +1

#525 Fix channel map selector
  static/js/src/public/details/channelMap.js
  static/js/src/public/details/channelMap.test.js
  templates/partial/_channel-map.html
Labels: Review: Code +1, Review: QA +1

#523 Consume libraries API
  requirements.txt
  static/sass/_pattern_p-navigation.scss
  templates/details/libraries/libraries_layout.html
  webapp/store/data/library_a.py
  webapp/store/data/library_b.py
  webapp/store/logic.py
  webapp/store/mock.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#526 Add metatags for details pages
  templates/about/glossary.html
  templates/about/governance.html
  templates/about/index.html
  templates/about/manifesto.html
  templates/about/publishing.html
  templates/base_layout.html
  templates/contact-us.html
  templates/details/details_layout.html
  templates/docs/document.html
  templates/docs/search.html
  templates/overview.html
  templates/store.html
  templates/thank-you.html
Labels: Review: Code +1, Review: QA +1

#528 Add discourse.juju.is url for old docs links
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#529 Use large summary for non charm pages
  templates/base_layout.html
  templates/details/details_layout.html
Labels: Review: Code +1, Review: QA +1

#530 Add generated sitemap.xml
  templates/sitemap.xml
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#534 Add structure data markup
  templates/base_layout.html
  templates/details/details_layout.html
Labels: Review: Code +1, Review: QA +1

#536 Fix metadata
  templates/base_layout.html
Labels: Review: Code +1

#537 Add metadata for tutorials pages
  templates/base_layout.html
  templates/tutorials/index.html
  templates/tutorials/tutorial.html
Labels: Review: QA +1

#524 Add platform icons
  static/sass/styles.scss
  templates/partial/_entity-card.html
Labels: Review: Code +1, Review: QA +1

#538 Get all OS for a charm
  templates/partial/_entity-card.html
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#522 Show featured charms by default
  static/js/src/public/store/filters.js
  static/js/src/public/store/filters.test.js
  templates/partial/_filters.html
  templates/store.html
  webapp/helpers.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#541 Update empty state for docs
  static/sass/styles.scss
  templates/details/empty-docs.html
Labels: Review: Code +1, Review: QA +1

#539 Fix channel map on libraries tab
  templates/details/libraries/library.html
Labels: Review: Code +1, Review: QA +1

#545 Stop indexing pages not ready
  templates/docs/document.html
  templates/topics/kubernetes.html
  templates/tutorials/index.html
Labels: Review: Code +1, Review: QA +1

#547 Prefix charms install instructions
  templates/details/_details-header.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#548 Update feature charms
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#550 Update empty state actions
  templates/details/actions.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#558 Add juju instruction tooltip
  static/sass/styles.scss
  templates/details/_details-header.html
Labels: Review: Code +1, Review: QA +1

#553 Update meta description homepage
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#562 Remove windows from platforms
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#561 Refactor search view
  templates/partial/_filters.html
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#559 Fix search results filters
  static/js/src/public/store/filters.js
Labels: Review: Code +1, Review: QA +1

#551 Add CTA for more operators
  static/js/src/public/store/filters.js
  static/js/src/public/store/filters.test.js
  templates/partial/_filters.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#560 Fix spacing for info icon on libraries page
  templates/details/libraries/libraries_layout.html
Labels: Review: Code +1, Review: QA +1

#569 Fix 'all' category filter
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#590 Update butto text
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#589 Remove featured and other filters
  static/js/src/public/store/filters.js
  static/js/src/public/store/filters.test.js
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#588 Fix hidden heading when jumping between sections
  templates/details/configure.html
Labels: Review: Code +1, Review: QA +1

#596 Style emojis from discourse
  static/sass/_charmhub_p-tutorial.scss
Labels: Review: Code +1, Review: QA +1

#594 Maintenance mode
  .env
  .github/workflows/pr.yml
  Dockerfile
  konf/site.yaml
  templates/maintenance.html
  webapp/decorators.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#595 Rename Kubernetes to CAAS
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#593 Update branding color
  static/sass/_charmhub_footer.scss
  static/sass/_pattern_p-strip.scss
  static/sass/styles.scss
  templates/details/_details-header.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#597 Remove featured and other filters
  static/js/src/public/store/filters.js
  static/js/src/public/store/index.js
  templates/partial/_entity-card.html
  templates/partial/_filters.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#601 Fix a miss bit of blue
  static/sass/_pattern_p-strip.scss
Labels: Review: Code +1, Review: QA +1

#602 Implement static features list and platform filtering
  .prettierignore
  .prettierrc
  static/js/src/base/highlight.js
  static/js/src/public/store/filters.js
  templates/partial/_featured-charms.html
  templates/partial/_filters.html
  webapp/feature.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#603 Fix feature typo charms
  webapp/feature.py
Labels: Review: Code +1

#599 Kubernetes tooltips
  static/sass/styles.scss
  templates/details/_details-header.html
Labels: Review: Code +1, Review: QA +1

#604 Slightly reduce the logo size
  static/sass/_pattern_p-navigation.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#605 Update author names
  templates/partial/_filters.html
  webapp/feature.py
Labels: Review: Code +1

#606 Platform tooltips
  static/js/src/public/store/filters.js
  static/sass/_pattern_p-card.scss
  templates/partial/_featured-charms.html
Labels: Review: Code +1, Review: QA +1

#607 Hide featured on filter of platforms
  static/js/src/public/store/filters.js
Labels: Review: Code +1, Review: QA +1

#608 Fix tooltips
  static/js/src/public/store/filters.js
Labels: Review: Code +1, Review: QA +1

#609 Use cloudinary with lazy loading for charm icons
  static/js/src/public/store/filters.js
  templates/partial/_featured-charms.html
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#616 Rename categories
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#617 Added missing field for libraries API
  webapp/store/logic.py
Labels: Review: Code +1

#620 Update discourse module
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#619 Add tutorials to the site
  static/sass/_pattern_p-card.scss
  templates/partial/_footer.html
  templates/partial/_navigation.html
  templates/tutorials/index.html
Labels: Review: Code +1, Review: QA +1

#610 Kubernetes logo
  templates/details/_details-header.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#621 Update feature charm list
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#623 Search template
  templates/store-search.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#618 Make filtering work
  static/js/src/public/store/filters.js
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#624 Update feature charms
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#626 Hide feature on show all button
  static/js/src/public/store/filters.js
Labels: Review: Code +1, Review: QA +1

#627 Remove the malformed list mark up
  templates/partial/_filters.html
Labels: Review: Code +1

#631 Disable actions until data is ready
  static/js/src/public/store/filters.js
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#633 Fix meta image for missing icon
  templates/details/details_layout.html
Labels: Review: Code needed, Review: QA needed

#629 Cleanup filters.js
  static/js/src/public/store/buildCharmCard.js
  static/js/src/public/store/filters.js
Labels: Review: Code +1, Review: QA +1

#635 Remove hover effect on disabled filters
  static/js/src/public/store/filters.js
  static/sass/_charmhub_p-filter.scss
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#639 Update manifesto page copy
  templates/about/manifesto.html
Labels: Review: Code +1, Review: QA +1

#640 Lowercase search queries
  templates/store-search.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#641 Filters JS refactor
  static/js/src/public/store/charms.js
  static/js/src/public/store/index.js
  templates/partial/_filters.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#628 Proposing a clean up of the filter component
  static/sass/_charmhub_p-filter.scss
  static/sass/_charmhub_p-layout-store.scss
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#644 Remove duplicate search on large screens
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#648 Remove featured and others from filters
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#643 Change login URL
  templates/publisher/bundles.html
  templates/publisher/charms.html
  webapp/login/views.py
Labels: Review: Code needed, Review: QA needed

#649 Update styles for manifesto link
  templates/maintenance.html
  templates/overview.html
  templates/store-search.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#642 Make charm install snippet selectable
  templates/details/_details-header.html
Labels: Review: Code +1, Review: QA +1

#650 Update featured charms
  templates/partial/_filters.html
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#652 Consume real charm libraries
  webapp/store/views.py
Labels: Review: Code +1

#655 Disable category filters until data loads
  static/js/src/public/store/charms.js
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#656 Change missing var name
  webapp/store/views.py
Labels: Review: Code needed, Review: QA needed

#662 Update tutorial link
  templates/details/empty-docs.html
Labels: Review: Code +1, Review: QA +1

#657 Improve the filter checkboxes
  static/sass/styles.scss
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#659 Redirect upper case URLs for packages
  webapp/config.py
  webapp/decorators.py
  webapp/store/views.py
Labels: Review: Code needed, Review: QA needed

#653 Remove underline hero link
  static/sass/_pattern_p-link.scss
  static/sass/styles.scss
  templates/details/libraries/libraries_layout.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#663 Publisher charm listing view
  requirements.txt
  templates/publisher/listing.html
  webapp/decorators.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#666 Add GA click events to navigation.js
  static/js/src/public/navigation-events.js
  templates/base_layout.html
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#669 Update graylog-k8s to be featured
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#671 Add suru pattern to details pages
  static/sass/_pattern_p-strip.scss
  templates/details/_details-header.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#674 Make the featured count dynamic
  templates/partial/_filters.html
Labels: Review: Code +1, Review: QA +1

#680 Download library endpoint
  webapp/store/views.py
Labels: Review: Code needed, Review: QA needed

#682 Request an extra field from the API
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#685 Added multiple sitemaps
  requirements.txt
  templates/sitemap/sitemap-links.xml
  templates/sitemap/sitemap-operators.xml
  templates/sitemap/sitemap.xml
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#675 Fix integration chart being cropped on wide screens
  static/js/src/public/details/integrate/index.js
  static/sass/_pattern-p-integration-charts.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#684 Integrate API for POST listing page
  requirements.txt
  templates/publisher/charms.html
  templates/publisher/listing.html
  templates/publisher/publisher_layout.html
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#686 Fix publisher settings page
  templates/publisher/listing.html
  templates/publisher/settings.html
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#670 Update flask base
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#660 Add download dropdown to library page
  static/sass/_charmhub_p-contextual-menu.scss
  static/sass/styles.scss
  templates/details/libraries/libraries_layout.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#691 Add empty state
  templates/details/details_layout.html
Labels: Review: Code +1, Review: QA +1

#689 Add register charm name and dispute pages
  static/sass/_charmhub_publisher.scss
  static/sass/_pattern_p-button-group.scss
  static/sass/charmhub_utils.scss
  static/sass/styles.scss
  templates/details/actions.html
  templates/details/libraries/libraries_layout.html
  templates/partial/_header-publisher-packages.html
  templates/partial/_tabs-publisher-packages.html
  templates/publisher/bundles.html
  templates/publisher/charms.html
  templates/publisher/publisher_layout.html
  templates/publisher/register-name-dispute/index.html
  templates/publisher/register-name-dispute/thank-you.html
  templates/publisher/register-name.html
  templates/publisher/settings.html
  webapp/publisher/views.py
Labels: Review: Code +1 (with changes), Review: QA +1, Review: UX +1

#693 Update integrate page icons design
  static/sass/_pattern_grid.scss
  static/sass/_pattern_p-media-object.scss
  templates/details/integrate.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#696 Fix details overview page header on mobile
  static/sass/_charmhub_p-header.scss
  static/sass/_pattern_p-image.scss
  static/sass/_pattern_p-strip.scss
  static/sass/_pattern_p-tooltip.scss
  static/sass/styles.scss
  templates/details/_details-header.html
  templates/partial/_channel-map.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1
