Repository canonical/charmhub.io, pull requests merged in 2020-04, with the labels that each got.

#35 Upgrade vanilla to 2.9.0 & add side navigation to home page
  package.json
  static/sass/_pattern_p-strip.scss
  static/sass/_patterns_side-navigation.scss
  static/sass/styles.scss
  templates/partial/_side-navigation.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#38 32 update side nav on details page
  static/sass/styles.scss
  templates/partial/_tab-configuration.html
  templates/partial/_tab-docs.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#48 Add charm and bundle dummy data to python
  static/sass/_pattern_p-media-object.scss
  templates/details.html
  templates/partial/_side-navigation.html
  templates/partial/_tab-overview.html
  webapp/app.py
  webapp/charmhub.py
Labels: Review: Code +1, Review: QA +1

#51 Update 404 and 500 pages design
  static/sass/_pattern_p-image.scss
  static/sass/styles.scss
  templates/404.html
  templates/500.html
  templates/partial/_footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#52 42 replace details data with context
  templates/partial/_tab-actions.html
  templates/partial/_tab-configuration.html
  templates/partial/_tab-history.html
  templates/partial/_tab-integrations.html
  templates/partial/_tab-overview.html
  webapp/charmhub.py
Labels: Review: Code +1, Review: QA +1

#53 Fix tabs order when js is disabled
  templates/details.html
Labels: Review: Code +1, Review: QA +1

#54 Update documentation link in footer
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1

#56 Add no-JS section separator on details page
  static/sass/_charmhub_p-separator.scss
  static/sass/styles.scss
  templates/partial/_tab-actions.html
  templates/partial/_tab-configuration.html
  templates/partial/_tab-contribute.html
  templates/partial/_tab-docs.html
  templates/partial/_tab-history.html
  templates/partial/_tab-integrations.html
  templates/partial/_tab-overview.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#58 Update flask-base to 0.5.1
  .circleci/config.yml
  .dockerignore
  .env
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#63 Make the whole card clickable
  static/sass/_pattern_p-card.scss
  templates/partial/_entity-card.html
  webapp/charmhub.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#64 Update navigation
  static/sass/styles.scss
  templates/about.html
  templates/base_layout.html
  templates/collections.html
  templates/index.html
  templates/partial/_navigation.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#65 Add global nav
  .circleci/config.yml
  package.json
  templates/base_layout.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#70 Fix docker image to build JS
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#68 Remove the grid from the body
  static/sass/styles.scss
  templates/base_layout.html
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1

#69 Move collections to store
  templates/partial/_navigation.html
  templates/store.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#66 Add store module
  .env
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#72 Remove loader from the store page
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#73 Store backend magic
  requirements.txt
  templates/partial/_entity-card.html
  webapp/app.py
  webapp/config.py
  webapp/error_handling.py
  webapp/store/__init__.py
  webapp/store/content/data.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#75 Update to focal
  Dockerfile
  entrypoint
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#76 Combine API data with details page data
  requirements.txt
  templates/details.html
  templates/partial/_entity-card.html
  templates/partial/_tab-configuration.html
  templates/partial/_tab-contribute.html
  templates/partial/_tab-history.html
  templates/store.html
  webapp/store/content/data.py
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#74 Implement the vanilla search bar, pass through search queries
  templates/store.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#82 Removing a filter should stay on store page
  templates/partial/_side-navigation.html
  webapp/helpers.py
Labels: Review: Code +1, Review: QA +1

#83 Truncate summary in cards
  static/sass/_pattern_p-card.scss
  templates/partial/_entity-card.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#84 Add webpack
  .circleci/config.yml
  package.json
  static/js/base/base.js
  static/js/base/global-nav.js
  static/js/public/details.js
  static/js/public/store.js
  static/js/tabs.js
  templates/base_layout.html
  templates/details.html
  templates/store.html
  webpack.config.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#86 Fix docker build with webpack
  Dockerfile
Labels: Review: Code +1

#85 Modify p-card to use the p-button
  static/sass/_pattern_p-card.scss
  templates/partial/_entity-card.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#87 Improve card heights to avoid scrollbars on smaller screens
  static/sass/_pattern_p-card.scss
Labels: Review: Code +1, Review: QA +1

#91 Re-add missing truncation
  templates/partial/_entity-card.html
Labels: Review: Code +1, Review: QA +1

#88 Initial store JS to update the UI without page load
  static/js/public/store.js
  static/js/public/store/filters.js
  static/js/public/store/index.js
  templates/partial/_side-navigation.html
  templates/store.html
  webapp/store/views.py
  webpack.config.js
Labels: Review: Code +1, Review: QA +1

#92 Initial homepage data
  static/sass/_pattern_p-card.scss
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#90 Add bundle-icons to fake data cards
  package.json
  static/sass/_charmhub_p-bundle-icons.scss
  templates/partial/_entity-card.html
Labels: Review: Code +1, Review: QA +1

#94 Favicon
  templates/base_layout.html
Labels: Review: Code +1, Review: QA +1

#93 Update details page
  static/js/base/base.js
  static/js/base/polyfills.js
  static/js/public/details.js
  static/js/public/details/channelMap.js
  static/js/public/details/historyState.js
  static/js/public/details/index.js
  static/js/public/details/tableOfContents.js
  static/js/public/details/tabs.js
  static/sass/styles.scss
  templates/base_layout.html
  templates/details.html
  templates/partial/_channel-map.html
  templates/partial/_partial-documentation.html
  templates/partial/_tab-actions.html
  templates/partial/_tab-configuration.html
  templates/partial/_tab-docs.html
  templates/partial/_tab-integrations.html
  templates/partial/_tab-overview.html
  templates/partial/_tabs-navigation.html
  webapp/helpers.py
  webapp/store/content/data.py
  webapp/store/views.py
  webpack.config.js
Labels: Review: Code +1, Review: QA +1

#95 Some more update
  static/js/public/details/channelMap.js
  static/sass/styles.scss
  templates/details.html
  templates/partial/_channel-map.html
  templates/partial/_tab-overview.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1
