Repository canonical/charmhub.io, pull requests merged in 2021-01, with the labels that each got.

#747 Update feature list
  webapp/feature.py
Labels: Review: Code needed, Review: QA needed

#756 Show bundles in search results
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#765 Make topology available as JSON
  static/js/src/public/details/index.js
  static/js/src/public/details/topology.js
  templates/details/details_layout.html
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1

#766 Add favicon
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#763 Change url on filter selection
  static/js/src/public/store/buildCharmCard.js
  static/js/src/public/store/charms.js
  static/js/src/public/store/index.js
  static/sass/_charmhub_l-store.scss
  static/sass/_pattern_p-card.scss
  static/sass/_pattern_p-navigation.scss
  static/sass/styles.scss
  templates/details/_details-header.html
  templates/partial/_featured-charms.html
  templates/partial/_navigation.html
  templates/partial/_topic-cards.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#771 Configure tab: Respect new lines
  templates/details/configure.html
Labels: Review: Code +1, Review: QA +1

#772 Align text baseline on homepage
  templates/store.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#776 Make bundles visible on homepage
  static/js/src/public/store/buildCharmCard.js
  static/js/src/public/store/buildPackageCard.js
  static/js/src/public/store/index.js
  static/js/src/public/store/packages.js
  static/sass/_charmhub_p-bundle-icons.scss
  templates/store.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#777 Fix summary console error on charm details page
  static/js/src/public/details/index.js
  static/js/src/public/details/overview/index.js
  templates/details/actions.html
  templates/details/details_layout.html
  templates/details/docs.html
  templates/details/empty-docs.html
  templates/details/history.html
  templates/details/integrate.html
  templates/details/overview.html
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1

#780 Fix ubuntu series
  templates/partial/_channel-map.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#781 Get resources info from the API
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#783 Remove loading state if no filters are selected
  static/js/src/public/store/charms.js
Labels: Review: Code +1, Review: QA +1

#785 Wrap text properly on configure tab
  templates/details/configure.html
Labels: Review: Code +1, Review: QA +1

#787 Disable no charm filters on homepage
  static/js/src/public/store/charms.js
Labels: Review: Code +1 (with changes), Review: QA +1

#786 Fix search results page
  templates/store-search.html
Labels: Review: Code +1, Review: QA +1

#788 Add ellipsis to side navigation on configure tab
  static/sass/styles.scss
  templates/details/configure.html
Labels: Review: Code +1, Review: QA +1

#775 Add SVG topology to bundles
  static/js/src/public/details/index.js
  static/sass/_charmhub_p-topology.scss
  static/sass/_pattern_p-modal.scss
  static/sass/styles.scss
  templates/details/configure.html
  templates/details/overview.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#791 Add bundle overview page
  static/js/src/public/details/overview/index.js
  static/js/src/public/store/buildCharmCard.js
  static/js/src/public/store/buildPackageCard.js
  static/js/src/public/store/index.js
  static/js/src/public/store/packages.js
  static/sass/_charmhub_p-bundle-icons.scss
  static/sass/_charmhub_p-topology.scss
  static/sass/_pattern_p-modal.scss
  static/sass/styles.scss
  templates/details/_details-header.html
  templates/details/_details-tab-navigation.html
  templates/details/overview.html
  templates/store.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#793 Update feature charm icons
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#794 Update mariadb command
  webapp/feature.py
Labels: Review: Code +1, Review: QA +1

#797 Hide loading cards if no JS
  static/js/src/public/store/packages.js
  templates/store.html
Labels: Review: Code +1, Review: QA +1
