Repository canonical/charmhub.io, pull requests merged in 2021-02, with the labels that each got.

#802 Docs v3
  requirements.txt
  templates/details/docs.html
  templates/docs/document.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#803 Fix tutorials
  webapp/tutorials/views.py
Labels: Review: Code +1, Review: QA +1

#804 Charm docs: Fix side nav and remove 'Navigation' section
  requirements.txt
Labels: Review: Code needed, Review: QA needed

#807 Fix info tooltip on mobile
  static/js/src/base/base.js
  static/js/src/base/tooltip-icon-modal.js
  static/sass/_pattern_p-tooltip.scss
  static/sass/styles.scss
  templates/partial/_channel-map.html
Labels: Review: Code +1, Review: QA +1

#805 Changes for new API version
  requirements.txt
  templates/details/details_layout.html
  templates/partial/_channel-map.html
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#811 Fix packages.json endpoint
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#812 Build listing page mvp
  static/js/src/publisher/listing-page.js
  static/sass/styles.scss
  templates/publisher/listing.html
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#817 Fix JS filters when missing categories
  static/js/src/public/store/packages.js
Labels: Review: Code +1, Review: QA +1

#814 Get featured charms from API
  templates/partial/_featured-charms.html
  webapp/feature.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#822 Make save bar interactive on listing page
  static/js/src/publisher/listing-page.js
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#824 Add endpoints for publicise pages
  templates/publisher/publicise/embedded_cards.html
  templates/publisher/publicise/github_badges.html
  templates/publisher/publicise/publicise_layout.html
  templates/publisher/publicise/store_buttons.html
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#825 Fix fields management
  templates/details/overview.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#828 Add endpoint to serve the svg badge
  requirements.txt
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#827 Integrate canonicalwebteam.candid module
  requirements.txt
  webapp/login/candid.py
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#800 1805 build library page with latest designs
  requirements.txt
  static/js/src/public/navigation-events.js
  static/sass/_pattern_p-docstring.scss
  static/sass/_pattern_p-typography.scss
  static/sass/styles.scss
  templates/details/libraries/libraries_layout.html
  templates/details/libraries/library.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#815 Update homepage loading animation
  static/sass/_pattern_p-card.scss
  static/sass/styles.scss
  templates/base_layout.html
  templates/store.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#837 Remove redacted font
  static/sass/styles.scss
  templates/base_layout.html
Labels: Review: Code +1

#836 1872 update js on store page
  static/js/src/public/store/packages.js
  templates/publisher/publicise/github_badges.html
Labels: Review: Code +1, Review: QA +1

#838 Update search label for search results
  static/js/src/public/store/packages.js
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#840 Add query string value to the search input
  static/js/src/public/store/packages.js
  templates/partial/_navigation.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#829 Build publicise github badges page
  static/sass/_pattern_p-strip.scss
  static/sass/styles.scss
  templates/partial/_footer.html
  templates/publisher/publicise/github_badges.html
  templates/publisher/publicise/publicise_layout.html
  templates/publisher/publisher_layout.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#821 1820 add index to library page
  static/js/src/public/details/libraries/index.js
  static/js/src/public/details/libraries/tabSwitch.js
  static/sass/_pattern_p-docstring.scss
  templates/details/libraries/docstring.html
  templates/details/libraries/libraries_layout.html
  templates/details/libraries/source-code.html
  webapp/store/logic.py
  webapp/store/views.py
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1

#843 1858 build charmhub button page
  static/images/badges/ar/charmhub-black.svg
  static/images/badges/ar/charmhub-white.svg
  static/images/badges/bg/charmhub-black.svg
  static/images/badges/bg/charmhub-white.svg
  static/images/badges/bn/charmhub-black.svg
  static/images/badges/bn/charmhub-white.svg
  static/images/badges/de/charmhub-black.svg
  static/images/badges/de/charmhub-white.svg
  static/images/badges/en/charmhub-black.svg
  static/images/badges/en/charmhub-white.svg
  static/images/badges/es/charmhub-black.svg
  static/images/badges/es/charmhub-white.svg
  static/images/badges/fr/charmhub-black.svg
  static/images/badges/fr/charmhub-white.svg
  static/images/badges/it/charmhub-black.svg
  static/images/badges/it/charmhub-white.svg
  static/images/badges/jp/charmhub-black.svg
  static/images/badges/jp/charmhub-white.svg
  static/images/badges/pl/charmhub-black.svg
  static/images/badges/pl/charmhub-white.svg
  static/images/badges/pt/charmhub-black.svg
  static/images/badges/pt/charmhub-white.svg
  static/images/badges/ro/charmhub-black.svg
  static/images/badges/ro/charmhub-white.svg
  static/images/badges/ru/charmhub-black.svg
  static/images/badges/ru/charmhub-white.svg
  static/images/badges/tw/charmhub-black.svg
  static/images/badges/tw/charmhub-white.svg
  static/images/badges/ua/charmhub-black.svg
  static/images/badges/ua/charmhub-white.svg
  static/js/src/publisher/publicise.js
  static/sass/_pattern_p-separator.scss
  templates/publisher/publicise/store_buttons.html
  webapp/publisher/views.py
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#844 Limit character count for featured charm cards
  static/js/src/libs/truncate-string.js
  static/js/src/public/store/buildPackageCard.js
  templates/partial/_featured-charms.html
Labels: Review: Code +1 (with changes), Review: QA +1
