Repository canonical/charmhub.io, pull requests merged in 2021-07, with the labels that each got.

#1063 List charm collaborations
  templates/publisher/account-details.html
  templates/publisher/list.html
  templates/publisher/publisher_layout.html
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1065 Fix library fetch command
  templates/details/libraries/libraries_layout.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1071 Add resources tab
  static/sass/_charmhub_p-detail-inline-list.scss
  static/sass/_charmhub_p-detail-tabs.scss
  static/sass/styles.scss
  templates/details/resources.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1078 Get resources from API
  requirements.txt
  templates/details/_details-tab-navigation.html
  templates/details/resources.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1074 Update prettier config and add as GitHub action
  .github/workflows/pr.yml
  .prettierignore
  package.json
  static/js/src/public/details/channelMap.test.js
  static/js/src/public/store/packages.js
  static/js/src/publisher/components/multiselect.js
Labels: Review: Code +1, Review: QA +1

#1083 Fix meta description for machine charms
  templates/details/details_layout.html
Labels: Review: Code +1, Review: QA +1

#1082 Build charm resources page
  static/sass/_charmhub_p-detail-inline-list.scss
  static/sass/_charmhub_p-detail-tabs.scss
  static/sass/styles.scss
  templates/details/resources.html
  webapp/store/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#1084 Remove resources from charm details navigation
  templates/details/_details-tab-navigation.html
Labels: Review: Code +1, Review: QA +1

#1085 Increase width of resources digest key
  static/sass/_charmhub_p-detail-inline-list.scss
Labels: Review: Code +1, Review: QA +1

#1088 Update channels dropdown
  templates/partial/_channel-map.html
  webapp/helpers.py
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1092 Revert "Remove resources from charm details navigation"
  templates/details/_details-tab-navigation.html
Labels: Review: Code +1, Review: QA +1

#1089 Update spacing and text for resource table
  templates/details/resources.html
Labels: Review: Code +1, Review: QA +1

#1087 Fix tab focus on digest popup
  static/js/src/public/details/resources/index.js
  static/sass/_charmhub_p-detail-inline-list.scss
  templates/details/resources.html
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1 (with changes), Review: QA +1

#1093 Fix empty link errors
  templates/partial/_footer.html
  templates/partial/_navigation.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#1079 Add syntax highlighting to details page overview
  static/js/src/base/highlight.js
  templates/details/details_layout.html
Labels: Review: Code +1, Review: QA +1

#1094 Authentication changes
  requirements.txt
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#1097 source bundle icons from charm name
  templates/details/_details-header.html
Labels: Review: Code +1, Review: QA +1
