Repository canonical/charmhub.io, pull requests merged in 2021-05, with the labels that each got.

#986 Update badge for unit testing
  webapp/store/badges.py
Labels: Review: Code +1, Review: QA +1

#988 Update the store header content
  templates/partial/_header-strip.html
Labels: Review: Code +1, Review: QA +1

#989 Capture click for tooltip button on charm cards
  static/js/src/public/store/packages.js
  static/sass/_pattern_p-card.scss
  templates/partial/_featured-charms.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#991 Remove is-wide class and tidy up the layout on all pages
  static/sass/_pattern_grid.scss
  static/sass/charmhub_utils.scss
  templates/details/_details-header.html
  templates/details/_details-tab-navigation.html
  templates/details/actions.html
  templates/details/configure.html
  templates/details/docs.html
  templates/details/empty-docs.html
  templates/details/history.html
  templates/details/integrate.html
  templates/details/libraries/libraries_layout.html
  templates/details/overview.html
  templates/publisher/listing.html
  templates/publisher/publicise/embedded_cards.html
  templates/publisher/publicise/github_badges.html
  templates/publisher/publicise/store_buttons.html
  templates/publisher/register-name-dispute/index.html
  templates/publisher/register-name-dispute/thank-you.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#990 Add hero typer to homepage
  static/js/src/libs/typer.js
  templates/partial/_header-strip.html
  webpack.config.entry.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#1008 Update badges
  requirements.txt
  templates/partial/_channel-map.html
  webapp/store/badges.py
Labels: Review: Code +1, Review: QA +1

#1011 Enable typer on small screens
  templates/partial/_header-strip.html
Labels: Review: Code +1, Review: QA +1

#1013 Fix get docs from metadata.yaml
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#1020 Changes for Mattermost charm
  redirects.yaml
  webapp/store/badges.py
Labels: Review: Code +1, Review: QA +1

#1019 Make side nav sticky
  static/sass/_pattern_p-navigation.scss
  static/sass/styles.scss
  templates/details/actions.html
  templates/details/configure.html
Labels: Review: Code +1, Review: QA +1

#1022 Add jenkins-agent-k8s to ops badges
  webapp/store/badges.py
Labels: Review: Code +1, Review: QA +1

#1025 Fix side navigation
  templates/details/configure.html
  templates/details/libraries/libraries_layout.html
Labels: Review: Code +1, Review: QA +1
