Repository canonical/charmhub.io, pull requests merged in 2021-11, with the labels that each got.

#1170 Fix some issues with libraries
  templates/details/libraries/docstring.html
Labels: Review: Code +1, Review: QA +1

#1173 Use consistently LMA 2 in navigation
  templates/partial/_navigation.html
Labels: Review: Code +1

#1176 Fix logo height
  static/sass/_pattern_p-navigation.scss
Labels: Review: Code +1, Review: QA +1

#1177 Configure tab improvements
  templates/details/_details-header.html
  templates/details/configure-bundle.html
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1179 Get bundle docs
  templates/details/_details-tab-navigation.html
  webapp/store/logic.py
Labels: Review: Code +1

#1181 Fix broken link on unpublished charms page
  templates/publisher/list.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#1178 Show multiple OS in header
  static/sass/_charmhub_p-series-tag.scss
  templates/details/_details-header.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1, Review: Design +1
