Repository canonical/charmhub.io, pull requests merged in 2021-04, with the labels that each got.

#909 Add hiring link to global nav
  static/js/src/base/global-nav.js
Labels: Review: Code +1

#915 Fix icons on top of tooltip on libraries page
  templates/details/libraries/libraries_layout.html
Labels: Review: Code +1, Review: QA +1

#916 Add nightly linkchecker
  .github/workflows/linkchecker.yaml
Labels: Review: Code +1

#900 Return 404 when requesting publicise pages and charm is not published
  templates/publisher/publicise/publicise_empty.html
  webapp/publisher/views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#919 Get list of charms
  templates/details/_details-header.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#920 Add endpoint for bundle icons
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#921 Use title of an operator instead of id when defined
  templates/details/_details-header.html
  templates/partial/_featured-charms.html
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#923 Add missing field result.title for details pages
  webapp/store/views.py
Labels: Review: Code +1

#926 Add bundle icons to the homepage
  static/js/src/public/store/buildPackageCard.js
  static/js/src/public/store/packages.js
  templates/details/_details-header.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#928 Enable bundles
  static/js/src/public/store/buildPackageCard.js
  static/js/src/public/store/packages.js
  templates/details/_details-header.html
  templates/details/overview.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#930 Stop using platform, use base instead
  static/js/src/public/store/buildPackageCard.js
  static/js/src/public/store/packages.js
  static/js/src/publisher/publicise.js
  templates/details/_details-header.html
  templates/details/details_layout.html
  templates/partial/_channel-map.html
  templates/partial/_featured-charms.html
  templates/publisher/publicise/embedded_cards.html
  templates/store.html
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#929 Add icon to the list and listing pages
  static/sass/_pattern_heading-icon.scss
  templates/publisher/list.html
  templates/publisher/listing.html
Labels: Review: Code +1, Review: Design +1, Review: QA needed

#922 Fix homepage sub-title overlap
  static/js/src/libs/truncate-string.js
  static/js/src/public/store/buildPackageCard.js
  templates/partial/_featured-charms.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#936 Stop using format_slug in templates
  templates/details/_details-header.html
  templates/details/details_layout.html
  templates/embeddable-card.html
  webapp/handlers.py
  webapp/helpers.py
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#942 Fix base issues
  templates/partial/_channel-map.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#945 Add new footer
  static/sass/_pattern_p-icon.scss
  static/sass/styles.scss
  templates/partial/_footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#950 Upgade vanilla to 2.29
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#955 Redirection for jujucharms.com
  konf/site.yaml
Labels: Review: Code +1

#934 Implement fluid breakout layout on homepage
  static/js/src/public/store/buildPackageCard.js
  static/sass/_charmhub_l-store.scss
  static/sass/_charmhub_p-layout-store.scss
  static/sass/_pattern_l-fluid-breakout.scss
  static/sass/_pattern_p-card.scss
  static/sass/_pattern_p-search-box.scss
  static/sass/styles.scss
  templates/maintenance.html
  templates/partial/_featured-charms.html
  templates/partial/_header-strip.html
  templates/partial/_navigation.html
  templates/store.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#958 Fix index issue when no icons
  webapp/store/views.py
Labels: Review: Code needed

#941 Implement the new navigation
  package.json
  static/js/src/base/global-nav.js
  static/js/src/base/navigation.js
  static/js/src/base/navigation.test.js
  static/sass/_pattern_p-navigation.scss
  static/sass/_pattern_p-search-box.scss
  static/sass/_pattern_p-subnav.scss
  static/sass/styles.scss
  templates/base_layout.html
  templates/partial/_navigation.html
  webpack.config.entry.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#820 Remove cs prefix. juju will now deploy only with charm name
  templates/partial/_channel-map.html
  webapp/feature.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#959 Remove suru on details page
  templates/details/_details-header.html
Labels: Review: Code +1, Review: QA +1

#960 Use deployable-on field
  static/js/src/public/store/buildPackageCard.js
  static/js/src/public/store/packages.js
  templates/details/_details-header.html
  templates/partial/_featured-charms.html
  templates/store.html
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#966 Add manifesto in navigation
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#968 Support multiple lines for default values in the configuration screen
  templates/details/configure.html
Labels: Review: Code +1, Review: QA +1

#970 Remove links from store page
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#971 Update linux template to vm
  static/js/src/public/store/buildPackageCard.js
  templates/partial/_featured-charms.html
Labels: Review: Code +1, Review: QA +1

#969 Add notification to charm pages
  static/sass/charmhub_utils.scss
  static/sass/styles.scss
  templates/details/overview.html
  templates/partial/_channel-map.html
  webapp/store/views.py
Labels: Review: Code +1 (with changes), Review: QA +1

#973 Update footer links
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1

#972 Add framework labels to homepage cards
  static/js/src/public/store/buildPackageCard.js
  static/sass/_pattern_p-card.scss
  static/sass/styles.scss
  templates/partial/_featured-charms.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#975 Add functionality button
  static/js/src/public/store/buildPackageCard.js
  static/js/src/public/store/packages.js
  static/sass/_pattern_p-card.scss
  static/sass/_pattern_p-tooltip.scss
  templates/partial/_featured-charms.html
  templates/store.html
  webapp/store/badges.py
  webapp/store/views.py
Labels: Review: Design +1, Review: QA +1, Review: UX +1

#979 Add all badges and checks
  static/js/src/public/store/buildPackageCard.js
  templates/partial/_featured-charms.html
  templates/store.html
  webapp/store/badges.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#983 Fix if statement to show notification
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#980 Add extra charms just in case
  webapp/store/badges.py
Labels: Review: Code +1
