Repository canonical/charmhub.io, pull requests merged in 2021-03, with the labels that each got.

#849 1821 add args to library functions
  requirements.txt
  static/sass/_pattern_p-docstring.scss
  templates/details/libraries/docstring.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#845 1861 add endpoint for embeddable cards
  package.json
  static/js/src/publisher/publicise.js
  static/sass/charmhub_utils.scss
  static/sass/styles-embedded.scss
  templates/embeddable-card.html
  templates/publisher/listing.html
  templates/publisher/publicise/embedded_cards.html
  webapp/store/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#850 1894 upgrade list page with latest designs
  static/sass/_pattern_p-list.scss
  templates/partial/_header-publisher-packages.html
  templates/partial/_tabs-publisher-packages.html
  templates/publisher/bundles.html
  templates/publisher/charms.html
  templates/publisher/list.html
  templates/publisher/publicise/github_badges.html
  webapp/app.py
  webapp/login/views.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#853 Add libraries tab
  templates/details/_details-tab-navigation.html
Labels: Review: Code +1, Review: QA +1

#852 Update settings page with the latest design
  static/js/src/publisher/settings.js
  static/sass/_pattern_p-list.scss
  static/sass/_pattern_p-separator.scss
  templates/publisher/settings.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#854 Add empty state list page
  templates/publisher/list.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#858 Fix hidden content under the sticky nav bar on actions page
  templates/details/actions.html
Labels: Review: Code +1, Review: QA +1

#875 Connect settings page to the api
  static/js/src/publisher/settings.js
  templates/publisher/listing.html
  templates/publisher/settings.html
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#876 Fix navigation tab to be able to click on Actions when Configure is selected
  templates/details/_details-tab-navigation.html
  templates/details/actions.html
  templates/details/configure.html
Labels: Review: Code +1, Review: QA +1

#878 Display empty string if charm title is not set
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1

#880 Fix pixelated favicon
  templates/base_layout.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#883 Fix scroll on libraries page
  templates/details/libraries/libraries_layout.html
Labels: Review: Code +1, Review: QA +1

#885 Charmhub libraries page - layout improvements
  static/sass/_pattern_p-docstring.scss
  templates/details/details_layout.html
  templates/details/libraries/docstring.html
  templates/details/libraries/libraries_layout.html
Labels: Review: Code +1 (with changes), Review: QA +1

#892 Link to discourse documentation about libraries
  templates/details/libraries/introduction.html
Labels: Review: Code +1, Review: QA +1

#890 Fix missing use of variable
  templates/details/libraries/docstring.html
Labels: Review: Code +1, Review: QA +1

#891 Use creation date from API on library page
  templates/details/libraries/libraries_layout.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#893 Remove metrics and releases from the publisher pages navigation
  templates/publisher/publisher_layout.html
Labels: Review: Code +1, Review: QA +1

#895 Add bottom spacing on docs and actions empty pages
  templates/details/actions.html
  templates/details/empty-docs.html
Labels: Review: Code +1, Review: QA +1

#896 Refactor libraries endpoint to use the same code
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#897 Update register name page
  templates/publisher/listing.html
  templates/publisher/register-name.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#898 Hide published section on list page if no charms/bundles are published
  templates/publisher/list.html
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#899 Fix channel map to work when drop-down is changed
  templates/partial/_channel-map.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#902 Fix tooltip on charms page
  templates/publisher/list.html
Labels: Review: Code +1, Review: QA +1

#903 Fix duplicated id's on homepage
  templates/partial/_featured-charms.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#907 Remove tutorials and redirect to juju.is
  redirects.yaml
  templates/partial/_navigation.html
  templates/tutorials/index.html
  templates/tutorials/tutorial.html
  webapp/app.py
  webapp/tutorials/views.py
Labels: Review: Code +1 (with changes), Review: QA +1

#901 Remove categories mapping
  static/js/src/public/store/packages.js
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1
