Repository canonical/charmhub.io, pull requests merged in 2022-03, with the labels that each got.

#1268 Filter by architecture
  templates/details/_details-header.html
  templates/embeddable-card.html
  templates/partial/_channel-map.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#1270 [Details] Force readme content to be left-aligned
  static/sass/styles.scss
  templates/details/overview.html
Labels: Review: Code +1, Review: UX +1

#1269 [Topics] Always display 'See all topics' link
  templates/partial/_topics.html
Labels: Review: Code +1, Review: UX +1

#1273 Include and remove topic pages
  templates/partial/_navigation.html
  templates/partial/_topics.html
  templates/topics/index.html
  webapp/topics/topics.json
Labels: Review: QA needed, Review: Code +1

#1266 Remove references to LMA, as we will use a topic page for COS
  templates/partial/_footer.html
  templates/partial/_navigation.html
Labels: Review: Code +1

#1277 Redirect rules from jujucharms
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#1279 Remove sorting on packages.json
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1280 Change linux filter to VM
  static/js/src/public/store/buildPackageCard.js
  static/js/src/public/store/packages.js
  templates/embeddable-card.html
  templates/partial/_featured-charms.html
  templates/store.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#1283 Support Discourse redirects on topic pages
  webapp/topics/views.py
Labels: Review: Code needed, Review: QA needed

#1284 Handle 0 topics
  static/js/src/public/store/topics.js
  static/js/src/public/topics/filter.js
  templates/topics/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1290 [Topics] Update topic page to handle categories without topics
  static/js/src/public/topics/filter.js
  templates/topics/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1292 Download resources
  templates/details/resources.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1294 Better formatting for docstring functions
  templates/details/libraries/docstring.html
Labels: Review: Code +1, Review: QA +1

#1298 Vertically align os-logos
  static/sass/_charmhub_p-series-tag.scss
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#1303 Search redirect
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#1305 Redirection for openoperatorcollection.io
  konf/site.yaml
Labels: Review: Code +1

#1306 Added support for type hints
  requirements.txt
  templates/details/libraries/docstring.html
Labels: Review: Code +1, Review: QA +1
