Repository canonical/charmhub.io, pull requests merged in 2022-04, with the labels that each got.

#1314 Send robots=noindex if charm/bundle is unlisted
  templates/details/details_layout.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1318 Add 'Operator's Corner' topic
  webapp/topics/topics.json
Labels: Review: Code +1, Review: QA +1

#1319 Add dates for resources
  templates/details/resources.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1322 Update topics filters list
  static/sass/_pattern_l-fluid-breakout.scss
  templates/topics/index.html
Labels: Review: Code +1, Review: QA +1

#1324 Remove unused canonicalwebteam.search dependency
  requirements.txt
Labels: Review: Code +1

#1323 Align 'How to contribute a Topic' button
  static/sass/styles.scss
  templates/topics/document.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1327 Increase width of embedded cards on smaller screen
  webapp/topics/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1329 Embedded 404 page
  static/sass/_pattern_p-card.scss
  templates/embeddable-404.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Review: Design +1, Review: UX +1

#1333 Remove Juju warning message
  static/sass/styles.scss
  templates/partial/_channel-map.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1335 Fix homepage link color
  static/sass/_pattern_p-card.scss
Labels: Review: Code +1, Review: QA +1

#1338 Create security.txt
  requirements.txt
  security.txt
Labels: Review: Code +1, Review: QA +1

#1341 Remove libraries introduction
  templates/details/libraries/docstring.html
  templates/details/libraries/introduction.html
  templates/details/libraries/libraries_layout.html
  templates/details/libraries/no-libraries.html
  templates/details/libraries/source-code.html
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1337 Add ids to readme headers
  requirements.txt
  static/js/src/public/details/index.js
  static/sass/styles.scss
  webapp/helpers.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1
