Repository canonical/charmhub.io, pull requests merged in 2022-11, with the labels that each got.

#1420 Get interfaces data from GitHub and parse markdown file
  requirements.txt
  templates/interfaces/index.html
  webapp/app.py
  webapp/interfaces/__init__.py
  webapp/interfaces/logic.py
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1424 Add interfaces index page
  static/js/src/interfaces/index.tsx
  templates/interfaces/index.html
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#1425 fix requested channel not persistent when doc links are clicked
  templates/details/_side-nav.html
  templates/partial/_macros.html
Labels: Review: Code +1, Review: QA +1

#1428 WD-630 consume github api with token
  konf/site.yaml
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1430 WD-658 filter interfaces by status
  webapp/interfaces/logic.py
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1431 Remove link
  templates/partial/_footer.html
Labels: Review: Code needed

#1433 WD-664 add interfaces/interface-version endpoint
  webapp/interfaces/logic.py
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1434 Wd 659 fetch yaml for each interface
  webapp/interfaces/logic.py
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1435 WD-661 add provider and consumer count to /interfaces.json
  webapp/interfaces/logic.py
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1436 Add counts to interfaces table
  static/js/src/interfaces/components/InterfacesIndex/InterfacesIndex.tsx
Labels: Review: Code +1, Review: QA +1

#1437 Populate developer documentation section of interface
  package.json
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#1438 Populate interface page charms section
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1
