Repository canonical/charmhub.io, pull requests merged in 2022-12, with the labels that each got.

#1440 Add other charms section to interface page
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#1441 Create a shared CharmCard
  static/js/src/shared/components/CharmCard.tsx
  static/js/src/shared/types.ts
Labels: Review: Code +1

#1442 Update integrations tab to use react (WD-724, WD-508, WD-509)
  static/js/src/public/details/integrations/components/App/App.tsx
  static/js/src/public/details/integrations/components/App/index.ts
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
  static/js/src/public/details/integrations/components/InterfaceSection.tsx
  static/js/src/public/details/integrations/index.tsx
  static/js/src/public/details/integrations/types.ts
  static/js/src/shared/components/CharmCard.tsx
  templates/details/integrations.html
  webapp/store/views.py
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#1444 Populate interface page sidebar
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
Labels: Review: Code +1, Review: QA +1

#1446 Wd 892 markdown code blocks dont have newlines
  requirements.txt
  webapp/interfaces/logic.py
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1447 WD-891 update schema links to repo
  webapp/interfaces/logic.py
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1449 Fix markdown rendering on interface page
  package.json
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1453 Apply the expandable navigation to the topics pages
  static/js/src/base/docs-side-nav.js
  static/sass/styles.scss
  templates/topics/document.html
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#1454 Update navigation
  package.json
  static/js/src/base/navigation.js
  static/js/src/base/navigation.test.js
  static/sass/_pattern_p-navigation.scss
  static/sass/_pattern_p-subnav.scss
  static/sass/styles.scss
  templates/base_layout.html
  templates/partial/_navigation.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: Design +1, Review: UX +1

#1457 Change logo link
  templates/partial/_navigation.html
Labels: Review: Code needed, Review: QA needed
