Repository canonical/charmhub.io, pull requests merged in 2022-08, with the labels that each got.

#1390 Fix incorrect small-tag placement
  templates/partial/_footer.html
Labels: Review: Code +1, Review: QA +1

#1388 Combine "Overview" with "Docs"
  templates/details/_details-tab-navigation.html
  templates/details/_side-nav.html
  templates/details/docs.html
  templates/details/overview.html
  templates/partial/_macros.html
  webapp/helpers.py
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1391 Update mistune
  requirements.txt
  webapp/helpers.py
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1394 Prevent 404 on no resource page
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1395 Remove noise from PR template
  .github/pull_request_template.md
Labels: Review: Code needed
