Repository canonical/charmhub.io, pull requests merged in 2022-10, with the labels that each got.

#1403 SPA Icon validation
  .babelrc
  Dockerfile
  package.json
  static/js/src/public/icon-validator/index.tsx
  templates/icon-validator.html
  tsconfig.json
  webapp/app.py
  webpack.config.entry.js
  webpack.config.js
  webpack.config.rules.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1408 Integrations tab – skeleton
  static/sass/styles.scss
  templates/details/_details-tab-navigation.html
  templates/details/integrations.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Hacktoberfest, hacktoberfest-accepted

#1409 Add analytics to icon-validator
  templates/icon-validator.html
Labels: Review: Code +1, Hacktoberfest, hacktoberfest-accepted

#1411 Collaboration tab
  requirements.txt
  templates/publisher/collaboration.html
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1, Hacktoberfest, hacktoberfest-accepted

#1413 Add collaborator table with revoke functionality
  .eslintrc.js
  package.json
  static/js/src/publisher/collaborator/index.tsx
  templates/publisher/collaboration.html
  webapp/publisher/views.py
  webpack.config.entry.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Hacktoberfest, hacktoberfest-accepted

#1414 Move collaborators table to its own component
  package.json
  static/js/src/publisher/collaborator/components/App.tsx
  static/js/src/publisher/collaborator/components/Collaborators.tsx
  static/js/src/publisher/collaborator/components/CollaboratorsTable.tsx
  static/js/src/publisher/collaborator/components/InviteConfirmation.tsx
  static/js/src/publisher/collaborator/components/InvitesTable.tsx
  static/js/src/publisher/collaborator/index.tsx
  static/js/src/publisher/collaborator/types.ts
  static/js/src/publisher/collaborator/utils.tsx
  static/sass/styles.scss
  webapp/publisher/views.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1
