Repository canonical/charmhub.io, pull requests merged in 2023-10, with the labels that each got.

#1676 fix weirdly capitalixed package name
  static/js/src/public/store/buildPackageCard.js
Labels: Review: Code +1, Review: QA +1

#1677 fix undefined error in package action
  templates/details/actions.html
Labels: Review: Code +1, Review: QA +1

#1678 Update Search and Reset buttons in searchbar
  static/js/src/base/navigation.js
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#1679 Minimise docs footers
  templates/details/docs.html
  templates/details/overview.html
Labels: Review: Code +1, Review: QA +1

#1681 Update charmhub.io navigation to match Juju.is navigation
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#1680 Ensure channel persists on all navigation items
  templates/details/configure-bundle.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1683 Fix double navigation, and other edge-cases for charm docs - WD-6672
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1684 Create delete package endpoint
  requirements.txt
  webapp/publisher/views.py
Labels: Review: Code +1

#1685 Add button to de-register charms and bundles
  static/sass/styles.scss
  templates/publisher/list.html
Labels: Review: Code +1, Review: QA +1

#1674 Release beta store
  package.json
  requirements.txt
  static/js/src/public/store-details/buildPackageCard.js
  static/js/src/public/store-details/buildTopicCard.js
  static/js/src/public/store-details/index.js
  static/js/src/public/store-details/packages.js
  static/js/src/public/store-details/topics.js
  static/js/store/components/App/App.tsx
  static/js/store/components/App/index.ts
  static/js/store/components/Banner/Banner.tsx
  static/js/store/components/Banner/index.ts
  static/js/store/components/Packages/Packages.tsx
  static/js/store/components/Packages/index.ts
  static/js/store/components/Topics/Topics.tsx
  static/js/store/components/Topics/index.ts
  static/js/store/data/categories.js
  static/js/store/data/package-types.js
  static/js/store/data/platforms.js
  static/js/store/index.tsx
  static/js/store/types/index.ts
  templates/beta/store.html
  templates/details/overview.html
  templates/embeddable-card.html
  templates/store.html
  webapp/store/views.py
  webpack.config.entry.js
  webpack.config.rules.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1686 Add confirmation modal for unregistering charms and bundles
  static/sass/styles.scss
  templates/publisher/list.html
Labels: Review: Code +1, Review: QA +1

#1687 Update unregister modal text
  templates/publisher/list.html
Labels: Review: Code +1, Review: QA +1

#1688 Fix the width of the grid
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#1691 Fix search colour
  package.json
  static/sass/styles.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1693 Bump canonicalwebteam.discourse to 5.4.3
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#1692 Move search to homepage hero
  package.json
  static/js/src/base/navigation.js
  static/js/store/components/Banner/Banner.tsx
  static/js/store/components/Packages/Packages.tsx
  static/sass/styles.scss
  templates/partial/_navigation.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1694 Center homepage search
  static/js/store/components/Banner/Banner.tsx
Labels: Review: Code +1, Review: QA +1

#1695 Bump store components to fix categories sort
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1698 Bump the version of discourse module to v5.4.4
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#1699 add has-guardrails-to-package-metadata
  webapp/publisher/views.py
Labels: Review: Code +1

#1700 Update charm icon validator to include a preview.
  static/js/src/public/icon-validator/index.tsx
  templates/details/_details-header.html
  templates/icon-validator.html
Labels: Review: Code +1, Review: QA +1
