Repository canonical/charmhub.io, pull requests merged in 2023-03, with the labels that each got.

#1532 Swap provides and consumes on integrations tab
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
Labels: Review: Code +1, Review: QA +1

#1529 WD-2205 Add Kubeflow beta 1.7 banner
  .github/workflows/pr.yml
  templates/details/_details-header.html
  templates/partial/_kubeflow-beta-banner.html
  tests/test_context.py
  webapp/handlers.py
  webapp/helpers.py
Labels: Review: Code +1, Review: QA +1

#1534 Remove JAAS link from navigation
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#1533 Link directly to discourse post about how to write a topic page
  templates/topics/document.html
  templates/topics/index.html
Labels: Review: Code +1, Review: QA +1

#1536 add sub-navigation to a Documention dropdown list
  static/sass/_pattern_p-navigation.scss
  templates/partial/_navigation.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#1543 Add versioning to stylesheet
  templates/base_layout.html
Labels: Review: Code +1, Review: QA +1

#1546 removed version from channel map
  templates/partial/_channel-map.html
Labels: Review: Code +1, Review: QA +1

#1550 Get last modified date for interfaces
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1551 Add last modified date to interface page
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
Labels: Review: Code +1, Review: QA +1

#1553 Add ENVIRONMENT to konf
  konf/site.yaml
Labels: Review: Code +1

#1517 Create charmhub beta
  entrypoint
  requirements.txt
  templates/base_layout.html
  templates/embeddable-404.html
  templates/embeddable-card.html
  templates/interface-card-404.html
  templates/interface-card.html
  templates/publisher/list.html
  webapp/config.py
  webapp/handlers.py
  webapp/store-licenses.json
  webapp/store/views.py
  webapp_beta/app.py
  webapp_beta/beta_app.py
  webapp_beta/charmhub_bp.py
Labels: Review: Code +1, Review: QA +1

#1554 Add new route for beta store
  templates/beta/store.html
  webapp/store/views.py
Labels: Review: Code needed, Review: QA needed

#1555 Add packages page to beta store
  .eslintrc.js
  package.json
  static/js/beta-store/components/App/App.tsx
  static/js/beta-store/components/App/index.ts
  static/js/beta-store/components/Packages/Packages.tsx
  static/js/beta-store/components/Packages/index.ts
  static/js/beta-store/index.tsx
  templates/beta/store.html
  webpack.config.entry.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1558 Pull public table from readme
  webapp/interfaces/logic.py
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1559 Add navigation to collaborations tab
  static/js/src/publisher/collaborator/components/Collaborators.tsx
  static/js/src/publisher/collaborator/index.tsx
  templates/publisher/collaboration.html
Labels: Review: Code +1, Review: QA +1

#1562 Pass the schedule_banner helper to the template
  webapp/handlers.py
Labels: Review: Code needed, Review: QA needed

#1563 Revert "Disable banner for now"
  templates/details/_details-header.html
Labels: Review: Code +1, Review: QA +1

#1565 Update beta store cards
  package.json
  static/js/beta-store/components/Packages/Packages.tsx
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1566 Add pagination to beta store page
  static/js/beta-store/components/App/App.tsx
  static/js/beta-store/components/Packages/Packages.tsx
Labels: Review: Code +1, Review: QA +1
