Repository canonical/charmhub.io, pull requests merged in 2023-06, with the labels that each got.

#1601 Enable public facing metadata links
  requirements.txt
  templates/details/_side-nav.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1600 Filter featured charms that does not exist
  requirements.txt
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
  webapp/interfaces/logic.py
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1603 A couple of small integrations fixes
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
  static/js/src/shared/components/CharmCard.tsx
Labels: Review: Code +1, Review: QA +1

#1605 Allow `/t/<id>` format for docs
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#1607 Cleanup beta package code
  static/js/beta-store/components/App/App.tsx
  static/js/beta-store/components/Packages/Packages.tsx
Labels: Review: Code +1, Review: QA +1

#1608 Improve package loading state
  package.json
  static/js/beta-store/components/Packages/Packages.tsx
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1610 Reinstate call to improve docs for charms
  templates/details/overview.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1611 Temporary fix to use first "issues" instead of "bug-url"
  templates/details/_side-nav.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#1609 make names and links for bundle charms
  static/sass/_charmhub_p-bundle-icons.scss
  templates/details/_bundle_icon.html
  templates/details/overview.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1613 Add banner to beta store homepage
  package.json
  static/js/beta-store/components/Banner/Banner.tsx
  static/js/beta-store/components/Banner/index.ts
  static/js/beta-store/components/Packages/Packages.tsx
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1614 Add topics to homepage
  package.json
  static/js/beta-store/components/Packages/Packages.tsx
  static/js/beta-store/components/Topics/Topics.tsx
  static/js/beta-store/components/Topics/index.ts
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1615 a11y fixes
  package.json
  templates/partial/_navigation.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1616 Fix cards and loading cards showing at the same time
  static/js/beta-store/components/Packages/Packages.tsx
  static/js/beta-store/components/Topics/Topics.tsx
Labels: Review: Code +1, Review: QA +1

#1617 Show bundle card for bundles on beta store
  static/js/beta-store/components/Packages/Packages.tsx
Labels: Review: Code +1, Review: QA +1

#1618 Update store-components version
  package.json
  yarn.lock
Labels: Review: Code +1

#1619 add collapsible navigation to charm details page
  templates/details/_side-nav.html
  templates/partial/_macros.html
Labels: Review: Code +1, Review: QA +1

#1623 use PS5 registry
  konf/site.yaml
Labels: Review: Code +1

#1624 update store compoments to 0.21.0
  package.json
  yarn.lock
Labels: Review: Code +1

#1625 Update validator to take into account more factors
  static/js/src/public/icon-validator/index.tsx
Labels: Review: Code +1

#1626 Add Charm Maturity topic
  webapp/topics/topics.json
Labels: Review: Code +1, Review: QA +1

#1629 Fix grid on libraries docs
  templates/details/libraries/docstring.html
Labels: Review: Code +1, Review: QA +1
