Repository canonical/charmhub.io, pull requests merged in 2023-11, with the labels that each got.

#1704 Wd 6949 empty platform
  templates/details/_details-header.html
  templates/partial/_channel-map.html
  tests/test_search.py
  webapp/search/logic.py
Labels: Review: Code +1, Review: QA +1

#1705 Fix duplicate platforms showing on charms
  templates/details/_details-header.html
  templates/partial/_channel-map.html
Labels: Review: Code +1, Review: QA +1

#1711 Fix search endpoints, extra checks
  webapp/search/logic.py
Labels: Review: Code needed, Review: QA needed

#1710 Update canonicalwebteam.discourse version
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#1716 Fix display of bundle charms
  templates/details/overview.html
Labels: Review: Code +1, Review: QA +1

#1714 Add side navigation to integrations tab
  static/js/src/public/details/integrations/components/App/App.tsx
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
  templates/details/integrations.html
Labels: Review: Code +1, Review: QA +1

#1718 Only remove the juju notice
  templates/partial/_channel-map.html
Labels: Review: Code +1, Review: QA +1

#1720 Update store components
  package.json
  yarn.lock
Labels: Review: Code +1

#1719 add create-track endpoint
  requirements.txt
  webapp/publisher/views.py
Labels: Review: Code +1
