Repository canonical/charmhub.io, pull requests merged in 2023-02, with the labels that each got.

#1477 Add interfaces to charmhub navigation
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1478 Fix library download link
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1479 Fix charms without latest series not searchable
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#1482 Add flake8 and black as dependencies
  requirements.txt
Labels: Review: Code +1

#1483 Update sitemaps to remove juju redirects
  templates/sitemap/sitemap.xml
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1489 fix duplicate platforms
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#1492 fix wrong hostname in /configure WD-1814
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1493 Fix charms without stable/latest track breaking
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1495 Fix resource tab link WD-1812
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1496 Disable interfaces
  templates/partial/_navigation.html
Labels: Review: Code +1

#1488 Hide private methods from libraries
  templates/details/libraries/docstring.html
Labels: Review: Code +1, Review: QA +1

#1498 Better metadata
  templates/base_layout.html
  templates/details/details_layout.html
  templates/topics/document.html
  templates/topics/index.html
Labels: Review: Code +1, Review: QA +1

#1499 In progess
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
Labels: Review: Code +1

#1503 Fix charm track channel information
  templates/details/_details-header.html
  templates/partial/_channel-map.html
Labels: Review: Code +1, Review: QA +1

#1504 Update docs link to go to new SDK documentation
  templates/details/_side-nav.html
  templates/details/empty-docs.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1506 Consume = Provide, Provide = Consume
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
Labels: Review: Code +1, Review: QA +1

#1507 Remove filter for draft items
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1509 Update Interfaces table columns
  static/js/src/interfaces/components/InterfacesIndex/InterfacesIndex.tsx
  webapp/interfaces/logic.py
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1508 rename Tested Charms to Featured Charms on a Charmhub interface page
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
Labels: Review: Code +1, Review: QA +1

#1511 remove headings if there are no Featured Charms
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
Labels: Review: Code +1, Review: QA +1

#1513 Interface: Add Categories to each row
  webapp/interfaces/logic.py
Labels: Review: Code +1, Review: QA +1

#1514 Add metadata to interfaces page
  templates/interfaces/index.html
Labels: Review: Code +1, Review: QA +1

#1510 Enable interface pages for all interfaces
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
  static/js/src/interfaces/index.tsx
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1515 Disable interface pages for production
  webapp/interfaces/views.py
Labels: Review: Code +1

#1518 Remove interface version
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
  webapp/interfaces/logic.py
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1519 Remove version from interfaces index url
  static/js/src/interfaces/components/InterfacesIndex/InterfacesIndex.tsx
Labels: Review: Code +1, Review: QA +1

#1520 Use url path for links to github
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
Labels: Review: Code +1, Review: QA +1

#1516 added a related link to Specification archive for each interface
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
  static/sass/_pattern_p-icon.scss
Labels: Review: Code +1, Review: QA +1, Review: Design +1, Review: UX +1

#1524 Fix global nav
  package.json
  static/sass/_pattern_p-navigation.scss
  static/sass/styles.scss
  templates/base_layout.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1528 Fix account dropdown alignment
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1
