Repository canonical/charmhub.io, pull requests merged in 2023-07, with the labels that each got.

#1630 Preserve channel in docs
  templates/partial/_macros.html
Labels: Review: Code +1, Review: QA +1

#1631 Update link from /docs/olm to /docs/juju
  templates/partial/_footer.html
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#1628 Fix error message for icon-validator
  static/js/src/public/icon-validator/index.tsx
Labels: Review: Code +1

#1636 Update store components
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1637 change a heading and use a default icon for a charm bundle page
  templates/details/_bundle_icon.html
  templates/details/overview.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1639 Update fetching interfaces from readme markdown
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
  webapp/interfaces/logic.py
Labels: Review: Code +1, Review: QA +1
