Repository canonical/charmhub.io, pull requests merged in 2024-01, with the labels that each got.

#1731 Reset pagination on search
  static/js/store/components/Banner/Banner.tsx
Labels: Review: Code +1, Review: QA +1

#1733 Fix height of collaboration UI sidebar
  static/js/src/publisher/collaborator/components/Collaborators.tsx
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#1734 Add button to accept invites
  static/js/src/publisher/collaborator/components/Collaborators.tsx
Labels: Review: Code +1, Review: QA +1

#1735 Refactor collaborator invites
  static/js/src/publisher/collaborator/atoms/index.ts
  static/js/src/publisher/collaborator/components/App.tsx
  static/js/src/publisher/collaborator/components/Collaborators.tsx
  static/js/src/publisher/collaborator/components/CollaboratorsTable.tsx
  static/js/src/publisher/collaborator/components/InviteConfirmation.tsx
  static/js/src/publisher/collaborator/components/InvitesTable.tsx
  static/js/src/publisher/collaborator/index.tsx
  static/js/src/publisher/collaborator/utils.tsx
  templates/publisher/collaboration.html
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#1737 Add resend and reopen collaboration invites
  static/js/src/publisher/collaborator/components/Collaborators.tsx
  static/js/src/publisher/collaborator/components/InvitesTable.tsx
  static/js/src/publisher/collaborator/hooks/index.ts
  static/js/src/publisher/collaborator/utils.tsx
Labels: Review: Code +1, Review: QA +1

#1739 Refactor collaboration endpoint responses
  static/js/src/publisher/collaborator/hooks/index.ts
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#1740 Prevent duplicate invites from being created
  static/js/src/publisher/collaborator/components/Collaborators.tsx
Labels: Review: Code needed, Review: QA +1

#1744 update store components version to 0.48.0
  .github/workflows/pr.yml
  package.json
  yarn.lock
Labels: Review: Code +1

#1745 update cards to the same as integration cards from store components
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
  static/js/src/shared/components/CharmCard.tsx
  static/js/src/shared/types.ts
Labels: Review: Code +1, Review: QA +1

#1746 Update payload for revoking invites
  requirements.txt
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#1747 Accept and reject invites
  requirements.txt
  static/js/src/publisher/collaborator/components/App.tsx
  static/js/src/publisher/collaborator/components/Collaborators.tsx
  static/js/src/publisher/collaborator/components/InviteConfirmation.tsx
  static/js/src/publisher/collaborator/components/InvitesTable.tsx
  static/js/src/publisher/collaborator/hooks/index.ts
  static/js/src/publisher/collaborator/utils.tsx
  templates/publisher/accept-invite.html
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#1748 Fix validation error when creating an invite
  static/js/src/publisher/collaborator/components/Collaborators.tsx
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1750 Add collaborators table
  static/js/src/publisher/collaborator/components/Collaborators.tsx
  static/js/src/publisher/collaborator/components/CollaboratorsTable.tsx
  static/js/src/publisher/collaborator/components/InvitesTable.tsx
  static/js/src/publisher/collaborator/hooks/index.ts
  static/js/src/publisher/collaborator/utils.tsx
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#1751 Fix position of buttons on collaboration UI side panel
  static/js/src/publisher/collaborator/components/Collaborators.tsx
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1
