Repository canonical/charmhub.io, pull requests merged in 2024-03, with the labels that each got.

#1774 feat: redirect interfaces to draft if no "live" version found
  webapp/interfaces/views.py
Labels: Review: Code +1, Review: QA +1

#1776 Add publisher endpoint
  webapp/store/views.py
Labels: Review: Code +1

#1777 Add unit test for get_publisher_details
  tests/store/test_get_publisher_details.py
Labels: Review: Code +1

#1778 Change configure terminology
  redirects.yaml
  templates/details/_details-tab-navigation.html
  templates/details/configure-bundle.html
  templates/details/configure-charm.html
  webapp/store/views.py
Labels: Review: Code needed

#1773 Add inks for integrations
  package.json
  static/js/src/interfaces/components/DeveloperDocumentation/DeveloperDocumentation.tsx
  static/js/src/interfaces/components/DocumentationSection/DocumentationSection.tsx
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
  static/js/src/interfaces/components/MermaidDiagram/MermaidDiagram.tsx
  static/js/src/interfaces/components/MermaidDiagram/index.ts
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
  static/sass/styles.scss
  webapp/interfaces/views.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1
