Repository canonical/charmhub.io, pull requests merged in 2024-06, with the labels that each got.

#1841 fix: compiler warnings
  webapp_beta/beta_app.py
Labels: Review: Code +1

#1845 ci: add requirements and pylint to tics report step
  .github/workflows/coverage.yml
Labels: Review: Code +1, Review: QA +1

#1849 Add favicon
  static/images/favicon.png
  templates/base_layout.html
Labels: Review: Code +1, Review: QA +1

#1848 fix: integrations tab shows correct charms for each channel
  static/js/src/public/details/integrations/components/App/App.tsx
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
Labels: Review: Code +1, Review: QA +1

#1831 set coverage threshold
  codecov.yml
Labels: Review: Code +1

#1851 fix: add a chip to integration tabs when required property is set to true in metadata.yaml
  static/js/src/public/details/integrations/components/App/App.tsx
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
  static/js/src/public/details/integrations/components/__tests__/InterfaceItem.test.js
  static/js/src/public/details/integrations/types.ts
  webapp/store/views.py
Labels: Review: Code +1, Review: UX +1

#1857 fix: install js deps for tics
  .github/workflows/coverage.yml
Labels: Review: Code needed

#1859 chore: fix compiler warnings in src/publisher
  package.json
  static/js/src/publisher/components/multiselect.tsx
  static/js/src/publisher/graphs/activeDevices.ts
  static/js/src/publisher/graphs/dataProcessing.ts
  static/js/src/publisher/list-page.js
  static/js/src/publisher/listing-page.ts
  tsconfig.json
  webpack.config.entry.js
  webpack.config.rules.js
  yarn.lock
Labels: Review: Code +1 (with changes)
