Repository canonical/charmhub.io, pull requests merged in 2024-05, with the labels that each got.

#1814 Move collaborators to react app
  static/js/src/publisher-admin/components/SectionNav/SectionNav.tsx
  static/js/src/publisher-admin/components/SectionNav/__tests__/SectionNav.test.tsx
  static/js/src/publisher-admin/hooks/index.ts
  static/js/src/publisher-admin/hooks/useCollaboratorsQuery.ts
  static/js/src/publisher-admin/hooks/useInvitesQuery.ts
  static/js/src/publisher-admin/hooks/useRevokeMutation.ts
  static/js/src/publisher-admin/hooks/useSendMutation.ts
  static/js/src/publisher-admin/index.tsx
  static/js/src/publisher-admin/pages/Collaboration/Collaboration.tsx
  static/js/src/publisher-admin/pages/Collaboration/CollaboratorFilter.tsx
  static/js/src/publisher-admin/pages/Collaboration/Collaborators.tsx
  static/js/src/publisher-admin/pages/Collaboration/InviteCollaborator.tsx
  static/js/src/publisher-admin/pages/Collaboration/InviteConfirmationModal.tsx
  static/js/src/publisher-admin/pages/Collaboration/Invites.tsx
  static/js/src/publisher-admin/pages/Collaboration/__tests__/Collaboration.test.tsx
  static/js/src/publisher-admin/pages/Collaboration/__tests__/CollaboratorFilter.test.tsx
  static/js/src/publisher-admin/pages/Collaboration/__tests__/InviteCollaborator.test.tsx
  static/js/src/publisher-admin/pages/Collaboration/index.ts
  static/js/src/publisher-admin/routes/root.tsx
  static/js/src/publisher-admin/state/atoms.ts
  static/js/src/publisher-admin/state/selectors.ts
  static/js/src/publisher-admin/types/components/Collaborator.d.ts
  static/js/src/publisher-admin/types/components/Invite.d.ts
  static/js/src/publisher-admin/types/components/Publisher.d.ts
  static/js/src/publisher-admin/types/global.d.ts
  static/js/src/publisher-admin/types/index.d.ts
  static/js/src/publisher-admin/utils/QueryProvider.tsx
  static/js/src/publisher-admin/utils/RecoilObserver.tsx
  static/js/src/publisher-admin/utils/__tests__/getFilteredCollaborators.test.ts
  static/js/src/publisher-admin/utils/__tests__/getFilteredInvites.test.ts
  static/js/src/publisher-admin/utils/__tests__/getInvitesByStatus.test.ts
  static/js/src/publisher-admin/utils/__tests__/publisherMatchesFilterQuery.test.ts
  static/js/src/publisher-admin/utils/buildInviteTableRows.tsx
  static/js/src/publisher-admin/utils/getFilteredCollaborators.ts
  static/js/src/publisher-admin/utils/getFilteredInvites.ts
  static/js/src/publisher-admin/utils/getInvitesByStatus.ts
  static/js/src/publisher-admin/utils/index.ts
  static/js/src/publisher-admin/utils/isAccepted.ts
  static/js/src/publisher-admin/utils/isExpired.ts
  static/js/src/publisher-admin/utils/isPending.ts
  static/js/src/publisher-admin/utils/isRevoked.ts
  static/js/src/publisher-admin/utils/publisherMatchesFilterQuery.ts
  static/js/src/publisher/collaboration/atoms.ts
  static/js/src/publisher/collaboration/components/App.tsx
  static/js/src/publisher/collaboration/components/Collaboration.tsx
  static/js/src/publisher/collaboration/hooks.ts
  static/js/src/publisher/collaboration/index.tsx
  static/js/src/publisher/collaboration/test-utils.tsx
  static/js/src/publisher/collaboration/types/index.d.ts
  static/sass/styles.scss
  webapp/publisher/views.py
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#1815 Add Sentry to publisher app
  package.json
  static/js/src/publisher-admin/index.tsx
  static/js/src/publisher-admin/routes/root.tsx
  static/js/src/publisher-admin/types/global.d.ts
  templates/publisher/publisher.html
  webapp/config.py
  yarn.lock
Labels: Review: Code +1

#1816 Make sure Sentry DSN is accessible from the front-end
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#1818 fix: remove redirect canonical-kubernetes redirect
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#1819 Remove Sentry test code
  static/js/src/publisher-admin/routes/root.tsx
  static/js/src/publisher-admin/types/global.d.ts
Labels: Review: Code +1

#1820 Add Juju middle pages on Charmhub
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#1821 Construct integration index page
  static/js/src/interfaces/components/InterfacesIndex/InterfacesIndex.tsx
  tests/interfaces/test_interface_routes.py
  webapp/deprecated_interfaces/logic.py
  webapp/deprecated_interfaces/views.py
  webapp/integrations/logic.py
  webapp/integrations/views.py
Labels: Review: Code +1, Review: QA +1

#1822 Modify Github PR template for testing section
  .github/pull_request_template.md
Labels: Review: Code +1, Review: QA +1

#1823 refactor interface page and cache for a day
  webapp/integrations/logic.py
  webapp/integrations/views.py
Labels: Review: Code +1, Review: QA +1

#1825 fix: Update markdown for PR template for checkboxes
  .github/pull_request_template.md
Labels: Review: Code +1

#1827 feat: Create .jira_sync_config.yaml
  .github/.jira_sync_config.yaml
Labels: Review: Code needed

#1829 fix: handle discourse topic not found
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1830 ci: fix dotrun failing actions
  .github/workflows/pr.yml
Labels: Review: Code +1, Review: QA +1

#1836 docs: Update README.md to include coverage links
  README.md
Labels: Review: Code +1
