Repository canonical/charmhub.io, pull requests merged in 2024-07, with the labels that each got.

#1864 chore: Bump canonicalwebteam.discourse to 5.6.0 and vanilla to 4.14.0
  package.json
  requirements.txt
  templates/partial/_navigation.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1865 chore: Bumps canonicalwebteam.discourse version
  requirements.txt
  yarn.lock
Labels: Review: Code +1

#1868 fix: Fix compiler warnings in /static/js/src/libs
  static/js/src/libs/typer.js
  static/js/src/libs/typer.ts
  templates/partial/_header-strip.html
  webpack.config.entry.js
Labels: Review: Code +1

#1870 fix: Fix compiler warnings in static/js/src/public
  static/js/src/public/details/index.js
  static/js/src/public/details/index.ts
  static/js/src/public/details/integrate/index.ts
  static/js/src/public/icon-validator/index.tsx
  static/js/src/public/navigation-events.ts
  static/js/src/public/store-details/packages.ts
  templates/base_layout.html
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1

#1872 fix: Fix incorrect path names in HTML templates
  templates/base_layout.html
  templates/details/_side-nav.html
  templates/partial/_header-strip.html
  templates/topics/document.html
Labels: Review: Code +1

#1869 fix: Fix isolated module compiler error
  static/js/src/base/navigation.ts
Labels: Review: Code +1

#1873 fix: Tics security fix
  tests/test_decorators.py
  webapp/decorators.py
Labels: Review: Code +1, Review: QA +1

#1878 chore: Increase code coverage for /static/js/src/base/docs-side-nav.ts
  static/js/src/base/__tests__/docs-side-nav.test.ts
  static/js/src/base/docs-side-nav.ts
Labels: Review: Code +1

#1881 chore: increase static/js/src/base/navigation.ts code coverage
  static/js/src/base/__tests__/navigation.test.ts
  static/js/src/base/navigation.ts
Labels: Review: Code +1

#1884 chore: increase code cov - interfaces/components/CanonicalRelationsMeta
  static/js/src/interfaces/components/CanonicalRelationsMeta/CanonicalRelationsMeta.tsx
  static/js/src/interfaces/components/CanonicalRelationsMeta/__tests__/CanonicalRelationsMeta.test.tsx
Labels: Review: Code +1

#1885 chore: increase code cov - interfaces/components/CommunityRelationsMeta
  static/js/src/interfaces/components/CommunityRelationsMeta/__tests__/CommunityRelationsMeta.test.tsx
Labels: Review: Code +1

#1886 chore: Increase code cov - js/src/interfaces/DeveloperDocumentation
  static/js/src/interfaces/components/DeveloperDocumentation/__tests__/DeveloperDocumentation.test.tsx
Labels: Review: Code +1

#1888 chore: increase code cov interfaces/components/InterfaceDetailsLinks
  static/js/src/interfaces/components/InterfaceDetailsLinks/__tests__/InterfaceDetailsLinks.test.tsx
Labels: Review: Code +1

#1891 chore: increase code coverage interfaces/components/InterfaceDiscussion
  static/js/src/interfaces/components/InterfaceDiscussion/__tests__/InterfaceDiscussion.test.tsx
Labels: Review: Code needed

#1889 chore: increase code coverage interfaces/components/InterfaceDetailsNav
  static/js/src/interfaces/components/InterfaceDetailsNav/__tests__/InterfaceDetailsNav.test.tsx
Labels: Review: Code +1

#1892 chore: increase code coverage - /interfaces/components/InterfacesIndex
  static/js/src/interfaces/components/InterfacesIndex/__tests__/InterfacesIndex.test.tsx
Labels: Review: Code +1

#1893 chore: increase code coverage MermaidDiagram
  static/js/src/interfaces/components/MermaidDiagram/__tests__/MermaidDiagram.test.tsx
Labels: Review: Code +1

#1894 chore: increase code coverage for interfaces/ProvidingCharms
  static/js/src/interfaces/components/ProvidingCharms/__tests__/ProvidingCharms.test.tsx
  static/js/src/interfaces/components/testUtils.ts
Labels: Review: Code +1

#1895 chore: increase code coverage for interfaces/RequiringCharms
  static/js/src/interfaces/components/RequiringCharms/__tests__/RequiringCharms.test.tsx
Labels: Review: Code +1

#1897 chore: increase code coverage static/src/js/base/dynamic-contact-form.ts
  static/js/src/base/__tests__/dynamic-contact-form.test.ts
  static/js/src/base/dynamic-contact-form.ts
  static/js/src/public/details/channelMap.test.js
Labels: Review: Code needed

#1898 chore: increase code coverage for static/js/src/libs/arrays.js
  static/js/src/libs/__tests__/arrays.test.js
Labels: Review: Code +1

#1899 chore: increase code coverage for static/js/src/libs/debounce.js
  static/js/src/libs/__tests__/debounce.test.js
Labels: Review: Code +1

#1900 chore: increase code coverage for static/js/src/libs/highlight-nav.js
  static/js/src/libs/__tests__/highlight-nav.test.js
  static/js/src/libs/highlight-nav.js
Labels: Review: Code needed

#1901 chore: increase code coverage - static/js/src/libs/notification-close.js
  static/js/src/libs/__tests__/notification-close.test.js
Labels: Review: Code +1

#1903 chore: increase code coverage for static/js/src/libs/typer.ts
  static/js/src/libs/__tests__/typer.test.ts
  static/js/src/libs/typer.ts
Labels: Review: Code needed

#1904 chore: increase code coverage for `public/about/side-navigation.js`
  static/js/src/public/about/side-navigation.test.js
Labels: Review: Code +1

#1905 chore: increase code coverage for public/details/history/index.js
  static/js/src/public/details/history/__tests__/index.test.js
Labels: Review: Code +1

#1907 chore: increase code coverage for public/details/history/tableShowMore
  static/js/src/public/details/history/__tests__/tableShowMore.test.js
  static/js/src/public/details/history/tableShowMore.js
Labels: Review: Code +1

#1910 chore: increase code coverage for public/details/integrate/index.ts
  static/js/src/public/details/integrate/__tests__/index.test.ts
Labels: Review: Code +1

#1911 chore: deletes unused typer.ts file
  static/js/src/libs/__tests__/typer.test.ts
  static/js/src/libs/typer.ts
  webpack.config.entry.js
Labels: Review: Code +1

#1912 chore: increase code coverage for integrations/components/App/App.tsx
  static/js/src/public/details/integrations/components/App/App.tsx
  static/js/src/public/details/integrations/components/App/__tests__/App.test.tsx
Labels: Review: Code +1

#1913 chore: increase code coverage integrations/components/InterfaceItem.tsx
  static/js/src/public/details/integrations/components/__tests__/InterfaceItem.test.js
  static/js/src/public/details/integrations/components/__tests__/InterfaceItem.test.tsx
Labels: Review: Code +1

#1914 chore: increase code coverage for src/public/details/overview/index.js
  static/js/src/public/details/overview/__tests__/index.test.js
Labels: Review: Code +1

#1916 chore: increase code coverage for src/public/details/channelMap.ts
  static/js/src/public/details/__tests__/channelMap.test.ts
  static/js/src/public/details/channelMap.test.js
Labels: Review: Code +1

#1917 chore: increase code coverage for src/public/details/historyState.js
  static/js/src/public/details/__tests__/historyState.test.js
  static/js/src/public/details/historyState.test.js
Labels: Review: Code +1

#1918 chore: increase code coverage for static/js/src/public/details/index.ts
  static/js/src/public/details/__tests__/index.test.ts
  static/js/src/public/details/index.ts
Labels: Review: Code +1

#1919 chore: increase code coverage for src/public/details/tableOfContents.ts
  static/js/src/public/details/__tests__/tableOfContents.test.ts
  static/js/src/public/details/tableOfContents.ts
Labels: Review: Code +1

#1921 chore: increase code coverage - public/store-details/buildPackageCard.ts
  static/js/src/public/store-details/__tests__/buildPackageCard.test.ts
  static/js/src/public/store-details/buildPackageCard.ts
Labels: Review: Code +1

#1922 chore: increase code coverage - public/store-details/buildTopicCard.ts
  static/js/src/public/store-details/__tests__/buildTopicCard.test.ts
Labels: Review: Code +1

#1923 chore: increase code coverage for src/public/store-details/topics.js
  static/js/src/public/store-details/__tests__/topics.test.js
Labels: Review: Code +1
