Repository canonical/charmhub.io, pull requests merged in 2024-04, with the labels that each got.

#1783 add unit tests for get_interfaces and single_interface
  tests/interfaces/__init__.py
  tests/interfaces/test_interface_routes.py
Labels: Review: Code +1

#1787 Add a link to juju docs pages on the integration tab
  static/js/src/public/details/integrations/components/App/App.tsx
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1790 Remove block from creating expired or revoked invites
  static/js/src/publisher/collaboration/components/InviteCollaborator.tsx
  static/js/src/publisher/collaboration/utils/getInvitesByStatus.ts
Labels: Review: Code +1, Review: QA +1

#1791 Add email link for collaborator invite
  static/js/src/publisher/collaboration/atoms.ts
  static/js/src/publisher/collaboration/components/Collaboration.tsx
  static/js/src/publisher/collaboration/components/InviteCollaborator.tsx
  static/js/src/publisher/collaboration/components/InviteConfirmationModal.tsx
  static/js/src/publisher/collaboration/hooks.ts
Labels: Review: Code +1, Review: QA +1

#1792 Add collaboration to charm navigation
  templates/publisher/publisher_layout.html
Labels: Review: Code +1, Review: QA +1

#1788 WD-10256 Make the add topology icon directly trigger the file input and add a notification in the bundle listing form
  static/sass/_charmhub_publisher.scss
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1

#1794 add links to juju docs in header, action page and configure page
  static/sass/_charmhub_p-header.scss
  templates/details/actions.html
  templates/details/configure-bundle.html
  templates/details/configure-charm.html
  templates/partial/_channel-map.html
Labels: Review: Code +1, Review: QA +1

#1797 Fix the broken layout for Charm header
  templates/details/_details-header.html
  templates/partial/_channel-map.html
Labels: Review: Code +1, Review: QA +1

#1796 Create publisher application
  static/js/src/publisher-admin/components/SectionHeader.tsx
  static/js/src/publisher-admin/components/SectionNav.tsx
  static/js/src/publisher-admin/components/index.ts
  static/js/src/publisher-admin/index.tsx
  static/js/src/publisher-admin/pages/NotFound/NotFound.tsx
  static/js/src/publisher-admin/pages/NotFound/index.ts
  static/js/src/publisher-admin/routes/root.tsx
  templates/publisher/publisher.html
  webapp/publisher/views.py
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#1798 Fix link alignment on Charm header
  templates/partial/_channel-map.html
Labels: Review: Code +1, Review: QA +1

#1800 Update README.md
  README.md
Labels: Review: Code +1

#1802 Add endpoint for package data
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#1804 Fix collaborator invite link encoding
  static/js/src/publisher/collaboration/hooks.ts
Labels: Review: Code +1, Review: QA +1

#1803 Modify integrations tab
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
Labels: Review: Code +1, Review: QA +1

#1805 Modify provides or requires
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
Labels: Review: Code +1, Review: QA +1

#1808 Move publisher settings into React app
  babel.config.json
  static/js/src/publisher-admin/components/SectionHeader.tsx
  static/js/src/publisher-admin/components/SectionHeader/SectionHeader.tsx
  static/js/src/publisher-admin/components/SectionHeader/__tests__/SectionHeader.test.tsx
  static/js/src/publisher-admin/components/SectionHeader/index.ts
  static/js/src/publisher-admin/components/SectionNav/SectionNav.tsx
  static/js/src/publisher-admin/components/SectionNav/__tests__/SectionNav.test.tsx
  static/js/src/publisher-admin/components/SectionNav/index.ts
  static/js/src/publisher-admin/hooks/__tests__/usePackage.test.tsx
  static/js/src/publisher-admin/hooks/index.ts
  static/js/src/publisher-admin/hooks/usePackage.ts
  static/js/src/publisher-admin/index.tsx
  static/js/src/publisher-admin/mocks/index.ts
  static/js/src/publisher-admin/mocks/mockPackage.ts
  static/js/src/publisher-admin/pages/Settings/Settings.tsx
  static/js/src/publisher-admin/pages/Settings/__tests__/Settings.test.tsx
  static/js/src/publisher-admin/pages/Settings/index.ts
  static/js/src/publisher-admin/routes/root.tsx
  static/js/src/publisher-admin/state/atoms.ts
  static/js/src/publisher-admin/types/components/Package.d.ts
  static/js/src/publisher-admin/types/components/Publisher.d.ts
  static/js/src/publisher-admin/types/index.d.ts
  static/js/src/publisher-admin/utils/__tests__/capitalize.test.ts
  static/js/src/publisher-admin/utils/capitalize.ts
  static/js/src/publisher-admin/utils/index.ts
  static/js/src/publisher/settings.js
  templates/publisher/settings.html
  webapp/publisher/views.py
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1

#1810 Move publicise to react app
  static/js/src/publisher-admin/components/SectionNav/SectionNav.tsx
  static/js/src/publisher-admin/components/SectionNav/__tests__/SectionNav.test.tsx
  static/js/src/publisher-admin/index.tsx
  static/js/src/publisher-admin/pages/Publicise/Publicise.tsx
  static/js/src/publisher-admin/pages/Publicise/PubliciseBadges.tsx
  static/js/src/publisher-admin/pages/Publicise/PubliciseButtons.tsx
  static/js/src/publisher-admin/pages/Publicise/PubliciseCards.tsx
  static/js/src/publisher-admin/pages/Publicise/__tests__/Publicise.test.tsx
  static/js/src/publisher-admin/pages/Publicise/__tests__/PubliciseBadges.test.tsx
  static/js/src/publisher-admin/pages/Publicise/__tests__/PubliciseButtons.test.tsx
  static/js/src/publisher-admin/pages/Publicise/__tests__/PubliciseCards.test.tsx
  static/js/src/publisher-admin/pages/Publicise/index.ts
  static/js/src/publisher-admin/utils/index.ts
  static/js/src/publisher-admin/utils/languages.ts
  static/js/src/publisher/publicise.js
  templates/publisher/publicise/embedded_cards.html
  templates/publisher/publicise/github_badges.html
  templates/publisher/publicise/publicise_empty.html
  templates/publisher/publicise/publicise_layout.html
  templates/publisher/publicise/store_buttons.html
  webapp/publisher/views.py
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1

#1809 Reorder Integrations tab side navigation
  static/js/src/public/details/integrations/components/App/App.tsx
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1813 Try using codecov.yml
  .github/workflows/pr.yml
  codecov.yml
Labels: Review: Code +1, Review: QA +1

#1811 Move publisher listing view to React app
  jest.config.js
  jest.polyfills.js
  package.json
  static/js/src/publisher-admin/components/SectionNav/SectionNav.tsx
  static/js/src/publisher-admin/components/SectionNav/__tests__/SectionNav.test.tsx
  static/js/src/publisher-admin/index.tsx
  static/js/src/publisher-admin/pages/Listing/Listing.tsx
  static/js/src/publisher-admin/pages/Listing/ListingInputField.tsx
  static/js/src/publisher-admin/pages/Listing/__tests__/Listing.test.tsx
  static/js/src/publisher-admin/pages/Listing/__tests__/ListingInputField.test.tsx
  static/js/src/publisher-admin/pages/Listing/index.ts
  static/js/src/publisher-admin/utils/__tests__/capitalize.test.ts
  static/js/src/publisher-admin/utils/capitalize.ts
  static/sass/_charmhub_publisher.scss
  static/sass/styles.scss
  templates/publisher/listing.html
  webapp/publisher/views.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1
