Repository canonical/charmhub.io, pull requests merged in 2024-08, with the labels that each got.

#1926 chore: increase code coverage for publisher/components/multiselect.tsx
  static/js/src/publisher/components/__tests__/multiselect.test.tsx
Labels: Review: Code +1

#1927 chore: increase code coverage for src/publisher/graphs/activeDevices.ts
  static/js/src/publisher/graphs/__tests__/activeDevices.test.ts
Labels: Review: Code +1

#1928 chore: increase code coverage for publisher/graphs/dataProcessing.ts
  static/js/src/publisher/graphs/__tests__/dataProcessing.test.ts
Labels: Review: Code +1

#1929 chore: increase code coverage for static/js/src/publisher/list-page.js
  static/js/src/publisher/__tests__/list-page.test.js
Labels: Review: Code +1

#1930 chore: increase code coverage for static/js/src/publisher/listing-page
  static/js/src/publisher/__tests__/listing-page.test.ts
  static/js/src/publisher/listing-page.ts
Labels: Review: Code +1

#1931 fix: Remove production check in entryfile
  entrypoint
Labels: Review: Code +1

#1932 chore: increase code cov for publisher-admin/hooks/useCollaboratorsQuery
  static/js/src/publisher-admin/hooks/__tests__/useCollaboratorQuery.test.tsx
Labels: Review: Code +1

#1933 chore: increase code coverage - publisher-admin/hooks/useInvitesQuery.ts
  static/js/src/publisher-admin/hooks/__tests__/useInvitesQuery.test.tsx
Labels: Review: Code needed

#1934 chore: increase code coverage for publisher-admin/hooks/useReleases.ts
  static/js/src/publisher-admin/hooks/__tests__/useReleases.test.tsx
Labels: Review: Code +1

#1935 chore: increase code coverage for publisher-admin/hooks/usePackage.ts
  static/js/src/publisher-admin/hooks/__tests__/usePackage.test.tsx
Labels: Review: Code +1

#1936 chore: increase code coverage - publisher-admin/hooks/useRevokeMutation
  static/js/src/publisher-admin/hooks/__tests__/useRevokeMutation.test.tsx
Labels: Review: Code +1

#1937 chore: increase code coverage - publisher-admin/hooks/useSendMutation.ts
  static/js/src/publisher-admin/hooks/__tests__/useSendMutation.test.tsx
Labels: Review: Code +1

#1938 chore: increase code cov - pages/Collaboration/CollaboratorFilter
  static/js/src/publisher-admin/pages/Collaboration/__tests__/CollaboratorFilter.test.tsx
Labels: Review: Code +1

#1939 chore: increase code cov - pages/Collaboration/InviteConfirmationModal
  static/js/src/publisher-admin/pages/Collaboration/__tests__/InviteConfirmationModal.test.tsx
Labels: Review: Code +1

#1940 chore: increases code coverage - publisher-admin/pages/NotFound/NotFound
  static/js/src/publisher-admin/pages/NotFound/__tests__/NotFound.test.tsx
Labels: Review: Code +1

#1941 chore: increase code coverage for /publisher-admin/pages/Listing/Listing
  static/js/src/publisher-admin/pages/Listing/Listing.tsx
  static/js/src/publisher-admin/pages/Listing/__tests__/Listing.test.tsx
Labels: Review: Code +1

#1943 chore: increase code coverage for src/publisher-admin/routes/root.tsx
  static/js/src/publisher-admin/routes/__tests__/root.test.tsx
Labels: Review: Code +1

#1944 chore: increase code coverage for store/components/Banner/Banner.tsx
  static/js/store/components/Banner/__tests__/Banner.test.tsx
Labels: Review: Code +1

#1945 chore: increase code coverage for store/components/Packages/Packages.tsx
  static/js/store/components/Packages/__tests__/Packages.test.tsx
Labels: Review: Code +1

#1946 chore: increase code coverage for store/components/Topics/Topics.tsx
  static/js/store/components/Topics/__tests__/Topics.test.tsx
Labels: Review: Code +1

#1949 chore: increase code coverage for src/publisher/graphs/rendering.js
  static/js/src/publisher/graphs/__tests__/rendering.test.js
Labels: Review: Code +1

#1950 chore: increase code coverage for src/interfaces/components/App/App.tsx
  static/js/src/interfaces/components/App/__tests__/App.test.tsx
Labels: Review: Code +1

#1951 chore: increase code cov- src/interfaces/components/DocumentationSection
  static/js/src/interfaces/components/DocumentationSection/__tests__/DocumentationSection.test.tsx
Labels: Review: Code +1

#1952 chore: increase code coverage for interfaces/components/InterfaceDetails
  static/js/src/interfaces/components/InterfaceDetails/__tests__/InterfaceDetails.test.tsx
Labels: Review: Code +1

#1955 chore: increase code coverage for src/public/store-details/packages.ts
  static/js/src/public/store-details/__tests__/packages.test.tsx
Labels: Review: Code +1

#1959 chore: Clean up beta store
  entrypoint
  requirements.txt
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
  static/js/store/components/Packages/Packages.tsx
  webapp/app.py
  webapp/charmhub_bp.py
  webapp/decorators.py
  webapp_beta/app.py
  webapp_beta/beta_app.py
Labels: Review: Code +1, Review: QA +1

#1953 chore: increase code coverage for src/public/icon-validator/index.tsx
  static/js/src/public/icon-validator/__tests__/index.test.tsx
  static/js/src/public/icon-validator/index.tsx
Labels: Review: Code +1

#1957 chore: increase code coverage for src/public/navigation-events.ts
  static/js/src/public/__tests__/navigation-events.test.tsx
Labels: Review: Code +1

#1958 chore: add more tests to static/js/src/base/dynamic-contact-form.ts
  static/js/src/base/__tests__/dynamic-contact-form.test.ts
Labels: Review: Code +1

#1961 chore: fix failing tests and linting
  static/js/src/public/__tests__/navigation-events.test.tsx
  static/js/src/public/icon-validator/__tests__/index.test.tsx
  static/js/src/public/icon-validator/index.tsx
Labels: Review: Code +1

#1967 fix: Revert beta store cleanup
  entrypoint
  requirements.txt
  static/js/src/public/details/integrations/components/InterfaceItem.tsx
  static/js/store/components/Packages/Packages.tsx
  webapp/app.py
  webapp/decorators.py
  webapp_beta/app.py
  webapp_beta/beta_app.py
  webapp_beta/charmhub_bp.py
Labels: Review: Code +1, Review: QA +1

#1968 chore: fix configuration redirect
  redirects.yaml
  templates/details/_details-tab-navigation.html
  templates/details/configure-bundle.html
  templates/details/configure-charm.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1976 fix: update tests that use setTimeout
  static/js/src/base/__tests__/docs-side-nav.test.ts
  static/js/src/interfaces/components/InterfaceDetails/InterfaceDetails.tsx
  static/js/src/interfaces/components/InterfaceDetails/__tests__/InterfaceDetails.test.tsx
  static/js/src/public/__tests__/navigation-events.test.tsx
  static/js/src/public/docs/mermaid.js
  static/js/src/public/icon-validator/__tests__/index.test.tsx
  static/js/src/public/topics/__tests__/filter.test.ts
  static/js/src/public/topics/filter.ts
  static/js/src/publisher-admin/hooks/__tests__/useCollaboratorQuery.test.tsx
  static/js/src/publisher-admin/hooks/__tests__/useInvitesQuery.test.tsx
  static/js/src/publisher-admin/hooks/__tests__/usePackage.test.tsx
  static/js/src/publisher-admin/hooks/__tests__/useReleases.test.tsx
  static/js/src/publisher-admin/hooks/__tests__/useRevokeMutation.test.tsx
  static/js/src/publisher-admin/hooks/__tests__/useSendMutation.test.tsx
  static/js/src/publisher-admin/hooks/useCollaboratorsQuery.ts
  static/js/src/publisher-admin/hooks/useInvitesQuery.ts
  static/js/src/publisher-admin/hooks/usePackage.ts
  static/js/src/publisher-admin/pages/Collaboration/__tests__/Collaboration.test.tsx
  static/js/src/publisher-admin/pages/Collaboration/__tests__/CollaboratorFilter.test.tsx
  static/js/src/publisher-admin/pages/Collaboration/__tests__/InviteCollaborator.test.tsx
  static/js/src/publisher-admin/pages/Collaboration/__tests__/InviteConfirmationModal.test.tsx
  static/js/src/publisher/__tests__/listing-page.test.ts
  static/js/src/publisher/listing-page.ts
  static/js/store/components/Packages/__tests__/Packages.test.tsx
Labels: Review: Code +1

#1978 chore: Update security email address
  security.txt
Labels: Review: Code +1

#1983 fix: Update security expires date
  security.txt
Labels: Review: Code needed

#1985 chore: fix grammatical error on invites
  templates/publisher/accept-invite.html
Labels: Review: Code +1
