Repository canonical/charmhub.io, pull requests merged in 2025-01, with the labels that each got.

#2051 upgrade react types
  package.json
  static/js/src/publisher-admin/pages/Collaboration/InviteConfirmationModal.tsx
  static/js/src/publisher-admin/pages/Listing/__tests__/Listing.test.tsx
  static/js/src/publisher-admin/pages/Releases/Releases.tsx
  static/js/src/publisher-admin/utils/buildInviteTableRows.tsx
  static/js/src/store/components/EmptyResultSection/EmptyResultSection.tsx
  static/js/src/store/components/PackageList/PackageList.tsx
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2052 upgrade typescript packages
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2053 upgrade build tools dependencies
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2054 upgrade eslint packages
  eslint.config.mjs
  package.json
  requirements.txt
  static/js/src/base/tooltip-icon-modal.js
  static/js/src/libs/debounce.js
  static/js/src/libs/notification-close.js
  static/js/src/public/docs/docs-side-navigation.js
  static/js/src/public/store-details/packages.ts
  static/js/src/public/store-details/topics.js
  webpack.config.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2056 chore: upgrade date-fns and concurrently
  jest.polyfills.js
  package.json
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#2057 chore: upgrade undici package
  jest.polyfills.js
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2059 chore: upgrade node, sentry/react and remark-mermaidjs
  Dockerfile
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2060 chore: update internal dependencies
  package.json
  requirements.txt
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2061 Feature/update dependencies
  .github/workflows/pr.yml
  .github/workflows/publish-charm.yaml
  .github/workflows/publish-rock.yaml
  Dockerfile
  eslint.config.mjs
  jest.polyfills.js
  package.json
  requirements.txt
  static/js/src/base/tooltip-icon-modal.js
  static/js/src/libs/debounce.js
  static/js/src/libs/notification-close.js
  static/js/src/public/docs/docs-side-navigation.js
  static/js/src/public/store-details/packages.ts
  static/js/src/public/store-details/topics.js
  static/js/src/publisher-admin/pages/Collaboration/InviteConfirmationModal.tsx
  static/js/src/publisher-admin/pages/Listing/__tests__/Listing.test.tsx
  static/js/src/publisher-admin/pages/Releases/Releases.tsx
  static/js/src/publisher-admin/utils/buildInviteTableRows.tsx
  static/js/src/store/components/EmptyResultSection/EmptyResultSection.tsx
  static/js/src/store/components/PackageList/PackageList.tsx
  webpack.config.js
  yarn.lock
Labels: Review: QA +1

#2062 chore: update reserved name alert
  templates/publisher/register-name.html
Labels: Review: Code +1, Review: QA +1

#2063 chore: Fix handling of SCSS warnings
  package.json
  static/sass/_charmhub_p-sort.scss
  static/sass/_charmhub_releases.scss
  static/sass/_pattern_l-fluid-breakout.scss
  static/sass/_pattern_p-card.scss
  static/sass/_pattern_p-docstring.scss
  static/sass/_pattern_p-media-object.scss
  static/sass/_pattern_p-separator.scss
  static/sass/_pattern_p-tooltip.scss
  static/sass/styles-embedded.scss
  static/sass/styles.scss
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1

#2067 Re-introduce 25/75 split in the top navigation
  package.json
  static/js/src/base/global-nav.ts
  static/sass/styles.scss
  templates/partial/_navigation.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1
