Repository canonical/charmhub.io, pull requests merged in 2025-04, with the labels that each got.

#2116 fix create track stuck in pending
  static/js/src/publisher-admin/pages/Releases/Releases.tsx
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#2118 Wd 20431 fix collaborators
  static/js/src/publisher-admin/hooks/__tests__/useSendMutation.test.tsx
  static/js/src/publisher-admin/hooks/useSendMutation.ts
  static/js/src/publisher-admin/pages/Collaboration/Collaboration.tsx
  static/js/src/publisher-admin/pages/Collaboration/InviteCollaborator.tsx
  static/js/src/publisher-admin/pages/Collaboration/InviteConfirmationModal.tsx
  static/js/src/publisher-admin/pages/Collaboration/Invites.tsx
  static/js/src/publisher-admin/pages/Collaboration/__tests__/Collaboration.test.tsx
  static/js/src/publisher-admin/pages/Collaboration/__tests__/InviteCollaborator.test.tsx
  static/js/src/publisher-admin/pages/Collaboration/__tests__/InviteConfirmationModal.test.tsx
  static/js/src/publisher-admin/utils/__tests__/generateInviteToken.test.ts
  static/js/src/publisher-admin/utils/__tests__/getUniqueInvites.test.ts
  static/js/src/publisher-admin/utils/buildInviteTableRows.tsx
  static/js/src/publisher-admin/utils/generateInviteToken.ts
  static/js/src/publisher-admin/utils/getUniqueInvites.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#2121 feat: add tracing integration
  .github/workflows/deploy.yaml
  app.py
  charm/charmcraft.yaml
  requirements.txt
  webapp/observability/utils.py
  webapp/packages/logic.py
Labels: Don't merge

#2125 fix: make configuration description optional
  templates/details/configure-charm.html
Labels: Review: Code +1, Review: QA +1
