Repository canonical/charmhub.io, pull requests merged in 2025-06, with the labels that each got.

#2138 fix: Update Ubuntu logo for charm details
  static/js/src/publisher-admin/utils/__tests__/generateReleaseChannelRows.test.tsx
  static/js/src/publisher-admin/utils/generateReleaseChannelRows.tsx
  templates/details/_details-header.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2141 WD-20970 - feature: publisher charms page
  static/sass/_charmhub_publisher.scss
  static/sass/styles.scss
  templates/details/_card-partial.html
  templates/details/_details-header.html
  templates/details/publisher.html
  tests/store/test_get_publisher_details.py
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code needed, Review: QA needed

#2143 redirect postgresql docs to RTD
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#2147 new deployment flow
  .github/workflows/deploy.yaml
  .github/workflows/juju_deploy.yaml
  rockcraft.yaml
Labels: Review: Code +1, Review: QA +1
